### ISSUE TITLE
DoD passwords (where permitted) must be longer than 8 characters in length and other complexity requirements are imposed. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1015]
**Organization Name (N/A, if individual)**: DCMA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.1.1., 1
 
**Comment (Include rationale for comment)**:  DoD passwords (where permitted) must be longer than 8 characters in length and other complexity requirements are imposed. 
 

**Suggested Change**: Recommend stating that memorized secrets must be in compliance with government regulations.  "At least 8 characters" suggests that 8 is the minimum which is not true of all federal organizations and DoD requires the use of complexity.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
As with other guidelines in this document, agencies may impose more stringent requirements in order to further reduce authentication risk.

However, reliance on memorized secrets (passwords) for single-factor authentication, even with a longer minimum length, is discouraged. A second authentication factor is needed when there is any significant risk associated with mis-authentication.
