### ISSUE TITLE
Session management inherited properties and AAL levels

### ISSUE THREAD

**Issue by cbertagnolli** [usnistgov/800-63-3#103]
**Organization**: 1

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 4.4 Summary of Requirements & 7.1 Session Bindings

**Comment (Include rationale for comment)**:
 7.1 States
"The secret used for session binding SHALL be generated by the session host in direct response to an authentication event. A session SHOULD inherit the AAL properties of the authentication event which triggered its creation"

Primarily asking for clarification here. Let's say I do direct PIV authentication, establish an SSO session cookie for subsequent access, that SHOULD inherit the AAL3 "property" of the original authentication event? Essentially that session is now good for AAL3 required application with no further protections other than those stated (i.e., HTTPOnly, Secure Only, etc)? 

OR would it be AAL2 since essentially that cookie is a bearer token asserting that the presenter is that user?

**Suggested Change**:
Need clarification and how AAL levels/properties align with session state management and "bearer assertions". Expand with examples or more directly defined wording instead of current "inherit the AAL properties".

IF it should inherit AAL3, then AAL3 session states should require additional protections of them; such as doing risk-based session management to limit hijacking of a user session.

It's too easy for end-users to unknowingly send out session id's etc in header traces (and could probably painlessly be phished from most since the user would not be asked for their actual credential). While you can never fully protect from poor end-user behavior, there are things that can mitigate the risks. In the case of risk-based, if suddenly that session is coming from a different device, unknown geo-location, or other information then a forced re-authentication would ensure it was not a stolen session.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
One area where we're diverging a bit from earlier editions of SP 800-63 is whether browser cookies used to maintain session continuity are considered "assertions" and therefore subject to the holder-of-key requirement at LoA 4 (AAL 3 / FAL 4). The Guideline is moving away from the view that session cookies are considered assertions because browsers don't generally have a purely holder-of-key mechanism to maintain session state above the TLS layer. Cookies used in this way have to meet certain requirements listed in -63B section 7.1 (which was recently updated by https://github.com/usnistgov/800-63-3/pull/341/commits/224e81b793d131801c7461d7ed4014ea2359e84e).

The other thing to remember is that validity of session cookies at LoA4 / AAL 3 is very short, as specified in -63B section 4.3.4: maximum of 12 hours with session activity, but reauthentication is required following 15 minutes of inactivity. So session IDs sent out in traces, etc. will be of limited utility.

In your example of SSO, it depends on whether the verifier and the relying party are the same entity or not. If they are the same entity, a session cookie could be used. Otherwise, an assertion (holder of key at LoA 4) would be required.

Any suggestions on how to make this clearer in the (now revised) text would be appreciated.

**Comment by jimfenton** [comment]
I'll assume this was closed by #341. If you have further suggestions, please comment further or open a new issue.
