### ISSUE TITLE
How should the CSP require subscribers to surrender or prove destruction of any physical authenticator? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1064]
**Organization Name (N/A, if individual)**: SSA

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.4, 
 
**Comment (Include rationale for comment)**:  How should the CSP require subscribers to surrender or prove destruction of any physical authenticator?
 
How should the CSP require subscribers to surrender or prove destruction of any physical authenticator containing certified attributes signed by the CSP as soon as practical after revocation or termination takes place? 

§6.4 of 800-63B document does not clarify on how should the CSP  require subscribers to surrender or prove destruction of any physical authenticator containing certified attributes signed by the CSP as soon as practical after revocation or termination takes place.

**Suggested Change**: Supply clarification that this only applies to authenticators such as PIV cards containing certified attributes. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The document already states that this only applies to authenticators containing certified attributes. The manner of proof depends on the implementation, and would usually involve either surrender of the authenticator to the CSP or submission of a signed certificate of destruction.

Perhaps "certify destruction" rather than "prove destruction" is a better term.
