### ISSUE TITLE
Authenticator recovery should depend on the highest AAL of the subscriber's CSP account. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1163]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 8.3 Authentic-ator Recovery, 2
 
**Comment (Include rationale for comment)**:  Authenticator recovery should depend on the highest AAL of the subscriber's CSP account.
 
While this point is valid, surely it should be a restriction on leveraging any authenticator to manipulate or obtain another authenticator. To be effective, the constraint needs to apply to the overall strength of the subscribers account – AAL1, AAL2 or AAL3. For example, the user should not be able to use a AAL1 authentication method to obtain or manipulate a higher AAL2 or AAL3 set of authenticators.

**Suggested Change**: Maintain integrity by controlling authenticator recovery at the highest level for the account.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Section 8.3 is a security discussion relating to authenticator recovery. The normative requirements regarding authenticator recovery are in Section 6.1.2.3.

Rather than managing authenticator recovery based on the maximum strength of the subscriber account, we manage authenticators based on the principle that to recover an authenticator, an equivalent strength (and factor) or authenticator needs to be used. For example, in order to recover "something you have" it should not be possible to do so using only "something you know" because that might allow someone to leverage an AAL1 authentication into AAL2. Just because the subscriber has an authenticator at AAL3, we do not always require AAL3 for reissuance, because AAL is defined on a per-transaction basis.

However, on rereading this section, it should also point out that authenticators usable at AAL3 (hardware-based, verifier impersonation resistant, etc.) may not be issued based on a weaker "thing you have". This will be added.

**Comment by jimfenton** [comment]
On re-rereading Section 6.1, paragraph 2 of 6.1.2.1 includes the requirement that the subscriber authenticate at the same or higher AAL in order to bind a new authenticator at that AAL. This covers the issue I mentioned above regarding weaker binding of an authenticator usable at AAL3.
