### ISSUE TITLE
The clause “…does not need to uniquely identify the subject”, does not seem to add to the need to be unique in context. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1218]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2. Introduction, 1
 
**Comment (Include rationale for comment)**:  The clause “…does not need to uniquely identify the subject”, does not seem to add to the need to be unique in context. 
 
Even if there are a set of identity attributes that are generally sufficient for uniqueness within a jurisdictional context, arguably there is no set of attributes that are effectively globally unique.

**Suggested Change**: Explain or remove this clause.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The intent here is that a digital identity, while unique, does not necessarily need to provide all of the information needed to map the identity back to the subject (to the "carbon-based life form" in the case of a human subject). We will try to improve the wording because "uniquely identify the subject" does not seem to be clear enough.
