### ISSUE TITLE
Clarify AAL1 single factor requirement. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1221]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 2. Introduction, 6
 
**Comment (Include rationale for comment)**:  Clarify AAL1 single factor requirement.
 
If there needs to be a “single-factor” requirement for AALI,  the authenticator must be something you know, as something you have and something you are cannot be used singularly. The single-factor requirement unnecessarily restricts some two-factor authenticator solutions.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Please note that normative requirements for authentication at AAL1 are in Section 4.1; Section 2 is informative.

_Something you have_ is considered acceptable for authentication at AAL1. While physical authenticators have different threat characteristics from memorized secrets, both have limited overall security. _Something you are_ cannot be used singularly because of the requirements given in Section 5.2.3.

As shown in Section 4.1.1, a wide variety of authenticators, including two-factor authenticators, may be used at AAL1.
