### ISSUE TITLE
Clarify the AAL1 30 day requirement. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1230]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.1.3 Reauthen-tication, 
 
**Comment (Include rationale for comment)**:  Clarify the AAL1 30 day requirement.
 
This requirement is difficult to understand. Presumably the subscriber can’t have an active session for 30 days. If the environment has something like a “Remember me” preference function so that credentials don’t need to be re-entered, then the subscriber is typically being authenticated by something you have and there is no assured binding to the person by the use of a something you know or something you are factor authenticator.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The definition of _active session_ depends on the application: it could be a browser session with a non-persistent "session" cookie, or it could be a mobile application instance with an embedded secret that is, effectively, running all the time. Therefore, the guideline does not presume that a subscriber can't have an active session for 30 days.

Given that AAL1 provides only modest security, reauthentication is required relatively infrequently, but is still required because of the limitations imposed by the security of some session secrets, particularly cookies.

This comment also presumes that authentication at AAL1 cannot occur using only a physical authenticator; this will continue to be acceptable as described in #1229.

Some additional language (as above) on what constitutes a "session" probably belongs in Section 7.2, and forward references from Sections 4.x.3 to Section 7.2 would also be helpful.

**Comment by jimfenton** [comment]
Forward references were added by 5301ebfbeb97b7c67dd049b9591c784967498684
