### ISSUE TITLE
Clarify the AAL2 12 hour requirement. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1232]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.2.3 Reauthen-tication, 
 
**Comment (Include rationale for comment)**:  Clarify the AAL2 12 hour requirement.
 
This requirement is difficult to understand. Presumably the subscriber can’t have an active session for 12 hours. If the environment has something like a “Remember me” preference function so that credentials don’t need to be re-entered, then the subscriber is typically being authenticated by something you have and there is no assured binding to the person by the use of a something you know or something you are factor authenticator. Allowing reauthentication with a single authentication factor (presumably only a memorized secret) is AAL1 – the user is not being strongly reauthenticated.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The 12 hour requirement was written to not require multiple reauthentications by a subscriber that is actively using a session during an entire working day (but would, for example, require reauthentication upon resuming after a >30 minute lunch break). "Remember me" options typically involve the placement of a persistent cookie in the user's browser; in the absence of a session cookie, these would not be considered to establish a session (although this should perhaps be clarified in the document).

A session cookie or other session context of course can't be considered to be a something-you-have authenticator without making the reauthentication requirement at AAL2 meaningless. The question is whether other types of something-you-have authenticators that establish authentication intent, such as OTP devices, are sufficient. It is probably safer to require a different factor besides something you have because the session context is already something you have.

**Comment by jimfenton** [comment]
There is also a consistency problem between section 4.2.3 and section 7.2, which does clearly require the use of a memorized secret or biometric for reauthentication at AAL2.

**Comment by jimfenton** [comment]
Most of this is fixed by #1230.
