### ISSUE TITLE
Recommendation and requirements for cryptographic modules and devices for AAL3 is unclear. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1233]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.3 Authentica-tor Assurance Level 3, 
 
**Comment (Include rationale for comment)**:  Recommendation and requirements for cryptographic modules and devices for AAL3 is unclear.
 
It’s not clear why AAL3 primarily relies on cryptographic assurance. While this addresses the risk of transfer by duplication, it doesn’t strengthen the assurance of possession by the registered subscriber. For AAL3, a biometric in combination with a memorized secret and something you have, provides a stronger link to the subscriber without an extra test for the something you have authenticator. In most cases, a three-factor combination of different types appears to provide the best mitigation for the risks of discovery or transfer of an authenticator.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
AAL3 authenticators are cryptographic in order to be able to provide verifier compromise resistance (Section 5.2.7).

Very few three-factor authentication systems exist currently. Imposition of a three-factor requirement at AAL3 (which corresponds to the authentication requirements of the previous LOA4) would impose an enormous migration impact on existing authentication systems operating at that level, including the need to deploy biometric sensors at all endpoints.
