### ISSUE TITLE
Recommendation and requirements for biometrics at AAL3 is unclear. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1234]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 4.3.2 Authenticator and Verifier Requirements, 4
 
**Comment (Include rationale for comment)**:  Recommendation and requirements for biometrics at AAL3 is unclear.
 
By allowing for a biometric factor for AAL3, this paragraph seems to possibly conflict with 4.3.1. If all three factor types are used, the cryptographic test of the something you have may not effectively add much additional assurance.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Three factors will not be required at AAL3 (see #1233).

A multi-factor cryptographic device (one of the choices in 4.3.1) can be activated with a biometric. The cryptographic test of something you have is intended to verify the provenance of the biometric sensor, since an unknown sensor could facilitate a replay attack, not have the required performance characteristics, or not provide the needed liveness detection.
