### ISSUE TITLE
The 8 character length requirement is too restrictive for memorized secret when used with another factor. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1240]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 5.1.1.1 Memor-ized Secret Authenticators, 
 
**Comment (Include rationale for comment)**:  The 8 character length requirement is too restrictive for memorized secret when used with another factor.
 
The limit of 8 characters excludes the possibility of a 4-digit PIN – as for example widely used with credit cards, where the something you know could combine with a something you have or biometric authenticator.

**Suggested Change**: Amend requirement to apply to single factor use only.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
With the exception of common requirements like authentication, the requirements for authenticators are the same regardless of the AAL they are used at. This makes the requirements simpler and removes the natural tendency to chip away at the security of multi-factor authentication by saying, "it's OK if I make this authentication factor weaker because of the other factor." But different authentication factors address different threats.

The limit on a PIN is actually 6 digits, if the PIN is randomly chosen by the CSP. User-chosen 4-digit PINs can be relatively weak because of the non-uniform choices made by users.

This guideline is primarily directed at US government agencies; others are free to base their requirements on this guideline and make informed changes to the requirements, but that will not be its primary focus.
