### ISSUE TITLE
Some further explanation is required to explain why a subscriber should maintain two authenticators for each factor except memorized secrets. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1250]
**Organization Name (N/A, if individual)**: NZ Government

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: 6.1.2.1 Binding of an additional authenticator, 1
 
**Comment (Include rationale for comment)**:  Some further explanation is required to explain why a subscriber should maintain two authenticators for each factor except memorized secrets. 
 
While most users don’t particularly like two memorized secrets such as a password and security questions, effort is required to enroll a second what you have devices or a second biometric, and this will generally add substantial extra cost for the CSP/Verifier and in turn the SP.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
"Security questions", also known as knowledge-based authentication or pre-registered knowledge questions, are no longer acceptable for authentication because they are based on information that isn't secret.

The cost of issuing additional authenticators has to be balanced with the cost associated with handling account recovery requests. Availability of additional authenticators reduces the account recovery burden when authenticators are lost or damaged. Look-up secrets are good choices as backup authenticators because of their low cost even though they can be used for only a specific number of authentications.

**Comment by jimfenton** [comment]
The motivation behind this is to help the subscriber avoid having to go through a (potentially onerous) recovery process. We can add a forward reference to 6.1.2.3 where that is described.
