### ISSUE TITLE
IAL 2 remote options requires "Physical comparison performed remotely SHALL include presentation attack detection as specified in [SP 800-63B, Section 5.2.3]. " 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1265]
**Organization Name (N/A, if individual)**: Boeing

**Organization Type**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: 5.3.1 Identity Verification Methods, Table 5-3
 
**Comment (Include rationale for comment)**:  IAL 2 remote options requires  "Physical comparison performed remotely SHALL include presentation attack detection as specified in [SP 800-63B, Section 5.2.3]. "
 
This requirement introduces Presentation attack detection  (PAD) which is to be used for both physical or biometric comparison when performed remotely.

**Suggested Change**: Define Remote physical comparison performed with PAD.  (Remote physical comparison is not defined at all in SP 800-63B, Section 5.2.3 as referenced in SP 800-63A, Table 5-3 )
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Some adjacent issues arise with this excellent issue:

1.  What happens if matching fails?  Should we lock the 'identity' so an alternative proofing process is needed?
2.  Do we require PAD since we don't have an enrolled device
3.  If they fail biometrics do we take biometric verification off the table?

This is much bigger than just PAD and we need to resolve.
