### ISSUE TITLE
Definitions of Trust Anchor and Man-in-the-middle attack 

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#1274]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63B

**Reference (Include section and paragraph number)**:
 3

**Comment (Include rationale for comment)**:
 In section 3, the definition of Man-in-the-middle attack should be expanded to include attacks on authenticator enrollment or binding.

In section 3, the definition for a Trust Anchor is inadequate. A trust anchor may also have additional information (i.e., name, name constraints, policy constraints, etc.) and may be provisioned via a secure protocol (not simply built in or via out-of-band).

**Suggested Change**:
 Clarify and expand on the definitions of a "Man-in-the-middle attack" and a "Trust Anchor" in line with the comment. 

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The definition of man-in-the-middle attack should be generalized.

The definition of trust anchor should mention constraints. Provisioning which occurs outside the context of a particular authentication operation is considered to be out of band, and therefore covered by the current definition,

Tagging as 63-3 because the definitions are moving there.
