### ISSUE TITLE
Authentication from mobile devices 

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#1275]
### All Fields Are Required

**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63B

**Reference (Include section and paragraph number)**:
 4

**Comment (Include rationale for comment)**:
 In section 4, authentication from mobile devices may fall into some cracks in the current levels. For example, if a server interface that is intended to receive an OTP from a multi-factor OTP device via a mobile device were only "open" as a consequence of an action taken on the server via a multi-factor cryptographic device, would this count as AAL-3?

**Suggested Change**:

 Clarify whether the use case described in the comment could qualify as AAL-3.  
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This sounds like a very specific use case and there is not enough information here to determine with certainty whether it is AAL3. The primary concern would be making sure that there is a secure binding between the multi-factor cryptographic device and the OTP received from the mobile device. If the mobile device is what is being authenticated, most likely it would not be AAL3 because the OTP is not verifier impersonation resistant (a man-in-the-middle could intercept and use the OTP).
