### ISSUE TITLE
Mobile phone functioning as a multi-factor OTP device

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#1285]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
 1

**Document (63-3, 63A, 63B, or 63C)**:
63B

**Reference (Include section and paragraph number)**:
10.2.5
 
**Comment (Include rationale for comment)**:
 Section 10.2.5 should clarify that a web portal accessed via a multi-factor crypto device or an app on a mobile phone could function as a multi-factor OTP device. Current language seems biased towards dedicated devices. 

**Suggested Change**:

Clarify that a web portal accessed via a multi-factor crypto device or an app on a mobile phone could function as a multi-factor OTP device
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
A multi-factor OTP device is "something you have" plus either "something you know or are" and for that reason is oriented toward something in the possession of the claimant. A web portal, presumably remote from the claimant, does not do that. Without more information, it's not possible to judge this specific application, but it sounds like the subscriber authenticates with a web portal that generates an assertion that is used by the ultimate relying party. This would normally need to meet the requirements in SP 800-63C, _Federation and Assertions_.
