### ISSUE TITLE
Mailing an authenticator in a sealed envelope to a secure location to insufficient. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1312]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 7.1 (Threat Mitigation Strategies)
Table 7-2, Issuance, Disclosure

, 
 
**Comment (Include rationale for comment)**:  Mailing an authenticator in a sealed envelope to a secure location to insufficient.

 
 The process needs to consider:
1)      Opaqueness of the envelope
2)      Registered delivery to ensure non-repudiation

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
NSA had a similar comment so worth considering.

**Comment by BlankenshipG** [comment]
One could tie this to the AAL requirments tied to the LOA level the
authenticator would be acceptable for a LOA1 might not be accepted to a
LOA2 or that of a LOA3.  One also should take into consideration of if the
authenticator is in a active state or a transport state.  Based on the
combination of AAL mapped to LOA level one then could put requirments
around any transport state comprises validation check to allow a
authenticator activation.  This would allow a better way to validate the
AAL authenticator had not been tampered with based on the LOA it is to be
used at.   The process should include both technical controls and process
controls appropriate to the level of AAL that the token is being used at.

On Thu, Apr 6, 2017, 4:55 PM Paul Grassi <notifications@github.com> wrote:

NSA had a similar comment so worth considering.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/usnistgov/800-63-3/issues/1312#issuecomment-292317107>,
or mute the thread
