### ISSUE TITLE
Discussing usability aspects separately from security aspects may result in not meeting security requirements. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1321]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63A

**Reference (Include section and paragraph number)**: Section 10 (Usability)
10.2.3 (Out-of-Band),
Para 2,
Bullet 2

, 
 
**Comment (Include rationale for comment)**:  Discussing usability aspects separately from security aspects may result in not meeting security requirements.
 
Section 10.2.3 is about usability of out of band authentication. Discussing usability aspects separately from security aspects may result in not meeting security requirements.
Secure implementation is further complicated if the user can select the out-of-band channel and opts to use common protocols tagged as insecure (e.g., VoIP and SMTP). Two of the most commonly used secondary channel implementations (call-back and email) are at risk (See 5.1.3.1. Out-of-Band Authenticators):
1)      E-mail: Email is sent via SMTP - which could be intercepted by an attacker with access to any portion of the network between the server and the user.
2)      Call-back: If a user has switched to a VoIP phone service, any portion of the message could be intercepted by an attacker with access to the VoIP portion of the network. Call back use cases:
a.      A user provider is using Vonage (or other VoIP service). How would a CSP know that call-back to the user's phone number represents an unexpected risk?
Many federal and contractor organizations have deployed VoIP internally (i.e., throughout the enterprise). How would a CSP know that call-back to an organizational phone is an unexpected risk?

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is 63B

**Comment by jimfenton** [comment]
Email and VoIP are no longer supported as out-of-band authentication channels because they do not establish the possession of a specific device. There are multiple commercial services that can be used to determine if a given phone number is associated with a VoIP service; this is an appropriate topic for the implementation guide that is planned after this document suite is published.

The security sections are normative; the usability sections are informative. This should inform decisions should any conflict arise.
