### ISSUE TITLE
OAuth implementation details needed

### ISSUE THREAD

**Issue by cbertagnolli** [usnistgov/800-63-3#142]
**Organization**: 1

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 7.1.2. OAuth Tokens

**Comment (Include rationale for comment)**:
OAuth is briefly mentioned but without much context or additional information on (1) whether it is an allowable 'solution' or (2) security mitigation or implementation requirements.

It states "The presence of an OAuth access token SHALL NOT be interpreted by the RP to indicate the presence of the user, in the absence of other signals. " ....and, is that bad, good, or what am I supposed to do with that information? Does that mean the Resource Server should not accept an OAuth token without some "other signal"? If so, what other signals are available...an OpenID Connect token within the request that is signed by the IdP? Is an IdP signed JWT alone (without OpenID Connect) sufficient -- similar to a bearer SAML token? 

Is that even a proper interpretation...because having the token itself and presenting it as a signed object is still not proof the user is present at the time of the request. Just proof at some point some signed "assertion" was generated for them and now presented to the API by a client application.

OpenID Connect is also only mentioned in 63C under Federation, but not in 63B. If an organization is implementing OAuth internally then it may be leveraged during normal API access and authentication as well -- in that case it's not really only Federation.

Essentially more details and expansion of the framework is needed. 

**Suggested Change**:
Given how broad OAuth as a framework is, it would be good to dive into some details to ensure consistent and secure implementations. There's numerous ways it can be done, some reasonably secure, others not secure at all, and some cases where it should never be used. 

IF OAuth is allowable for protecting resources, NIST should provide a minimum set of requirements covering scenarios such as:
- Token creation: whether OpenID Connect or other mechanisms such as simply a signed JWT response is sufficient to prove user authentication
- Token refresh lifetimes and limits (e.g., do we follow normal user timeout maximum values)
- Transmission, storage, and mapping of user authenticated sessions to those tokens

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
Resource servers aren't dealing with user authentication, which is the focus of this document. The component being logged in to in OpenID Connect, which uses OAuth but isn't equivalent to it, is the _client_ application, and the log-in mechanism is the signed ID token as discussed elsewhere in this document (in -C's examples, specifically). 

While there may be benefit for government profiles of secure OAuth, this document is not the place for it. What we do want to do here is not let developers assume that if they have an OAuth token, then they should assume the user is logged in, as you say: "having the token itself and presenting it as a signed object is still not proof the user is present at the time of the request". 

API access is outside the scope of OpenID Connect, and within the purview of OAuth. Since this document is about authentication and not API access, we don't cover it here. However, since OpenID Connect is a federation protocol, we do.

Hopefully this clears things up.

**Comment by cbertagnolli** [comment]
Somewhat, I get where you're coming from with regards to it not being "authentication". 

The problem is while it's not directly "authentication" it does tie into management of an authenticated identity to access some resource via some asserted information; and much like authenticating directly to an RP (which has fairly clear requirements), an API is just another RP in the whole scheme of things and very open to problems/exploitation. 

If that doesn't belong here, that's fine. But sure would be good to have some place for it...For better or worse it doesn't seem OAuth is going anywhere and with such a loose framework it's really open to being done very poorly if there's no central guidance (at least not aware of one at the moment???). Was hoping since OAuth was mentioned now that there'd start being clearer direction on implementation requirements :).

**Comment by jricher** [comment]
Thanks for the feedback. 

An API is _not_ just another RP. Those are two very different roles, even in OpenID Connect. For more discussion of that see the discussion of the network layout decisions here http://www.cloudidentity.com/blog/2013/01/02/oauth-2-0-and-sign-in-4/ or the article on OAuth and authentication here http://oauth.net/articles/authentication/

In fact, part of the reason for the text in question above is to dissuade people from thinking that an API is an RP; we don't want people making that mistake and treating an OAuth access token as proof the user is present. That's why this goes under the "session management" section and not the "federation" section, since it's tempting to say "as long as the access token still works then the session must still be valid". That's simply not true at all: an RP needs to manage its own session state following the authentication event. If one result of the authentication event is an access token, then the access token can of course be used within the resulting session, but it can't be the only indicator.

We also think that OAuth is a good protocol and that having a document to define its use would be a good idea, but that does not belong in 800-63. Not only is this document about authentication, it's also intended to be technology agnostic as much as possible. Perhaps another document will fill that role, such as those being developed in the iGov working group of the OpenID Foundation.

**Comment by cbertagnolli** [comment]
Depends I suppose how you interpret it. The original "...in the whole scheme of things" was meant primarily that while not necessarily an "RP" in the traditional sense, in the grander picture of accessing a resource within the secure (hopefully) context of a user, it is; it's some service that is providing access to a software resource. If folks don't look at the whole end-to-end is when they'll fall into those very pitfalls referenced by simply chunking pieces off, treating them separately, and not taking into account all those very touchpoints.

Semantics aside, it won't be covered here so if it's picked up elsewhere, which would be great if it is, then can follow it there.
