### ISSUE TITLE
In addition to the System of Records Notice (SORN) and Privacy Impact Assessment (PIA)… 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1421]
**Organization Name (N/A, if individual)**: CMS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: Section 4.2 (Privacy Requirements),
Para 5
, 
 
**Comment (Include rationale for comment)**:  In addition to the System of Records Notice (SORN) and Privacy Impact Assessment (PIA)…
 
other privacy artifacts may be applicable to an agency offering or using a federated IdP or RP services. This can include Data Use Agreements, Matching Agreements, etc.
There is a need to clarify when these artifacts are needed.

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jamiedanker-nppd** [comment]
Consider adding reference in 4.2 Para 5 to the "following requirements apply specifically to agencies" after # 4  "Note: Consultation with the SAOP may identify whether the agency that is acting either as an IdP or an RP triggers additional privacy requirements (See Section 9.4)     Add language to Section 9.4 Agency Specific Privacy Compliance "Due to the many components of digital authentication.  **For example, other privacy artifacts may be applicable to an agency offering or using a federated IdP or RP services such as Data Use Agreements, Computer Matching Agreements, etc.  The SAOP can assist the agency in determining what additional requirements apply**
Believe we should point to the SAOP to provide guidance as to the agency's specific circumstance and whether additional compliance requirements apply.
