### ISSUE TITLE
"RP needs to determine if validated and verified attributes are required" 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1753]
**Organization Name (N/A, if individual)**: IRS

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 6.1, 
 
**Comment (Include rationale for comment)**:  "RP needs to determine if validated and verified attributes are required"
 

**Suggested Change**: validation should be always required:
if attribute is PIC((4)9), then 'A02B' is invalid. 
Verification might be unnecessary.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is not about validating input strings, etc. making sure types are proper and attacks like SQL injection is not possible. This is about stating that just because an RP may need an attribute (like favorite color for purposes of personalization) they don't need a 3rd party attribute provider to validate and verify that my favorite color is blue.
