### ISSUE TITLE
Since the guidance differentiates the Shalls and the Shoulds, and "should" indicated recommended guidance, request to change wording here.

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#1760]
**Organization Name (N/A, if individual)**: Social Security Administration (SSA)

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: 5.4
 
**Comment (Include rationale for comment)**:  Since the guidance differentiates the Shalls and the Shoulds, and "should" indicated recommended guidance, request to change wording here. 

First paragraph states the the suite specifies "baseline requirements" that agencies SHOULD implement. The second paragraph states that "agencies may determine to partially implement the NIST recommended guidance based on …" 

**Suggested Change**: Change the second paragraph to read, "Agencies may determine to implement the NIST baseline requirements…" so as not to confuse which requirements an agency may determine to implement. 

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
The MAY partially implement should be reworded to something like 'alternatives' while demonstrating comparability to the assessed xAL.

**Comment by paul-grassi** [comment]
Addressed by a prior edit.  Changes to text:

Agencies MAY determine` alternatives` to the NIST recommended guidance, for the assessed xALs, based on their mission, risk tolerance, existing business processes, special considerations for certain populations, availablity of data that provides similar mitigations to those described in this suite, or due to other capabilities that are unique to the agency.

Agencies SHALL demonstrate comparability of any `chosen alternative`, to include any compensating controls, when the complete set of applicable 800-63 requirements is not implemented. `For example, an agency may choose a National Information Assurance Partnership (NIAP) protection profile over FIPS, where the profile is equivalent (or stronger) than the FIPS requirements`. That said, agencies SHALL NOT alter the assessed xAL based on agency capabilities. Rather, the agency MAY `adjust their implementation` of solutions based on the agency's ability to mitigate risk via means not explicitly addressed by 800-63 requirements. The agency SHALL implement procedures to document both the justification for any departure from normative requirements and detail the compensating control employed.
