### ISSUE TITLE
Allow VoIP

### ISSUE THREAD

**Issue by cchan** [usnistgov/800-63-3#182]
**Organization**: 3

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.1.3.2

**Comment (Include rationale for comment)**: What is the rationale behind disallowing VoIP? I use a VoIP number for many of my 2FA services, and it's much easier to manage than a real phone, especially since I rather distrust my mobile phone company's security methods. Unless there's a specific vulnerability in allowing VoIP, I think the option should be given since VoIP is more or less equivalently insecure to "real" mobile SMS: the SMS protocol itself is the security bottleneck in both cases, not VoIP, and that's the reason for the deprecation anyway. Please correct me if I'm wrong; I probably am.

(Also, how would such a restriction be implemented to distinguish the two? Blacklists?)

(Doesn't seem adequately resolved in #168 #78 #19)

**Suggested Change**: Treat VoIP SMS the same way as plain old mobile SMS.

**Comment by ergood** [comment]
You're misunderstanding why it's disallowed. Re-read section 5.1.3: "_Two key requirements are that the device be uniquely addressable and that communication over the secondary channel be private. Some voice-over-IP telephone services can deliver text messages and voice calls without the need for possession of a physical device; these SHALL NOT be used for out of band authentication._"

This has nothing to do with relative strength of the communication channel, it's all about what you prove by successfully receiving the message. SMS proves access to a device (something you have); VoIP proves knowledge of a second password (something you know). Since this factor is being combined with the requirement that you provide a password, VoIP only proves you know two passwords, which is not acceptable. (Two different _types_ of factors are required)

**Comment by jimfenton** [comment]
The analysis by @ergood is correct. SMS to a VoIP number does not prove possession of a physical device (authenticator).

There are services that can be used to distinguish between landline, mobile, and VoIP phone numbers. For example, [Twilio](https://www.twilio.com/) has an [API](https://www.twilio.com/lookup) that will return information including line type. Note that this is an example and not an endorsement of a particular product; I'm sure there are other sources as well.
