### ISSUE TITLE
Out-of-Band Device Considerations at AAL3

### ISSUE THREAD

**Issue by BernieEllis** [usnistgov/800-63-3#1882]
Out-of-Band devices have several verification methods (Phone call, mobile app/push notification, OATH tokens) available to them. Are none of these methods acceptable at AAL3? If deemed not, why?

Thanks!

**Comment by jimfenton** [comment]
AAL3 requires that a hardware-based authenticator and that an authenticator providing verifier impersonation resistance be used.

"OATH tokens", if I understand you correctly, are things like RSA SecurID devices. These are considered single-factor OTP devices, not out-of-band devices, and are acceptable at AAL3 if used in conjunction with a memorized secret and a single-factor software crypto authenticator that provides verifier impersonation resistance.

Out-of-band authenticators are not considered hardware-based authenticators and do not provide verifier impersonation resistance. Therefore, they would need to be supplemented by a physical authenticator providing both of those characteristics, at which point the out-of-band authenticator would be redundant from the standpoint of AAL3 requirements. There is nothing preventing the use of out-of-band authenticators as an additional risk-reduction measure at AAL3, but in general they are do not satisfy AAL3 requirements by themselves.

**Comment by BernieEllis** [comment]
Thanks for the reply! 

I’m not sure why out-of-band devices aren’t considered to be hardware authenticators.

Smart cards themselves aren’t an authenticator either; the cryptographic keys/certificates on the card are. Obviously, you can’t get access to the private key on the card without knowing a pin.

On an out-of-band device, let’s say a mobile phone, some type of authenticator app would be similar to keys on the smart card. Also similar is that you need to use a pin to use the authenticator app. It doesn’t work without having the device.

According to the publication: “Manual entry of an authenticator output, such as out-of-band and OTP authenticators, SHALL NOT be considered verifier impersonation-resistant because the manual entry does not bind the authenticator output to the specific session being authenticated. In a MitM attack, an impostor verifier could replay the OTP authenticator output to the verifier and successfully authenticate.”
 
My thought here is that it only speaks to scenarios where the authenticator output is displayed (The code via SMS or displaying the OTP code in authenticator), but what about push notifications where the authenticator is transmitted by a known/possessed factor (The six digit phone Auth code, or touch ID on iOS devices) and not displayed on the device? I think this is an omission in the documentation and push notifications can be considered as impersonation-resistant the same as having a PIV/CAC card and entering the pin.

Thoughts?

**Comment by jimfenton** [comment]
Hardware-based authenticators are dedicated devices that in normal use are not reprogrammable. Out-of-band devices are typically things like smartphones that have significant software that can potentially be compromised.

Smart cards are, in fact, cryptographic hardware authenticators (typically multi-factor since they're usually activated with a PIN). Except possibly for forensic or sidechannel analysis, it isn't possible to extract the private key form a smart card. The nonce that is to be signed is passed to the smart card and the signed nonce is sent back. This is why they are considered more secure than non-hardware authenticators where the private key can potentially be accessed by malware.

The important characteristic of verifier impersonation resistance is that the authenticator output depend on the specific TLS (or other authenticated protected channel) session that the authenticator output is communicated over. This is not the case when out-of-band secrets or OTP codes are manually entered by a user. In contrast, the output of a PIV/CAC authenticator (or a smart card or other client TLS certificate) is calculated using secrets generated during channel setup, and cannot be used successfully in any other TLS session.

**Comment by BernieEllis** [comment]
No argument from me that a smart card is more secure. Is the verifier impersonation resistance the primary reason why out-of-band devices are not considered for AAL3? If so, I want to zoom in on that.

I'm not sure I follow this: "the authenticator output depend on the specific TLS (or other authenticated protected channel) session that the authenticator output is communicated over. This is not the case when out-of-band secrets or OTP codes are manually entered by a user".  

In the scenario of an out-of-band authenticator using **push notifications** the output (Entry of the pin, which is not displayed on the device) is specific to the authentication request/specific TLS session. It's not a rolling code that can be used any time for any session. The security PIN is not shown to the user at all, they must already know it. The notification is specifically sent at the time authentication is needed as a direct result of a user's access attempt. Is that that verifier impersonation resistant?

Thanks for the responses.
