### ISSUE TITLE
Man in the middle definitions 

### ISSUE THREAD

**Issue by FIDOAlliance** [usnistgov/800-63-3#189]
FIDO Alliance

800-63-3B 
section 5.1.3

This 800-63-3 mentions resistance to man-in-the-middle attacks.  The older 800-63-2 mentioned weak man-in-the-middle resistance and strong man-in-the-middle resistance.

Does the term in 63-3 relate to the old “weak” or “strong” MITM resistance (or is it different)? 

---

Organization:  2 = Industry

**Comment by jimfenton** [comment]
The language around MITM resistance will be clarified. Rather than the term "weak man-in-the-middle resistance" (which seems, well, weak) we will be distinguishing between man-in-the-middle resistance and authentication that binds more strongly to the server's identity, tentatively to be referred to as phishing resistance.

**Comment by jimfenton** [comment]
Current thought is to refer to "strong man-in-the-middle resistance" as "verifier impersonation resistance". Proposed text around this is being reviewed, and can be seen at https://github.com/jimfenton/800-63-3/commit/7ea140ddea1c4747aa460bc4655ab8337abefd9e

**Comment by jimfenton** [comment]
Resolved by #371.
