### ISSUE TITLE
Deprecating SMS OTP (and non Smart Phones)

### ISSUE THREAD

**Issue by kenpalla** [usnistgov/800-63-3#198]
**Organization**: Personal comment  ken palla

**Type**:  Banking

**Document (63-3, 63A, 63B, or 63C)**:  63B

**Reference (Include section and paragraph number)**:  5.1.3

**Comment (Include rationale for comment)**:  I agree there are better solutions than SMS OTP (e.g. mobile push notification).  But if a bank customer does not have the bank's mobile app on a Smart Phone, then I am limited to what authentication I offer.  So I have to address the use cases other than customer having bank mobile app.  These include:  1) customer has smart phone, but no bank mobile app, 2) customer has basic flip mobile phone (no apps allowed), customer has no mobile phone.  if I can identify which phone type my customer has (there are solutions that can tell me customer phone type, including VOIP), then maybe I limit SMS OTP (or maybe also OOB Phone) to those customers without the bank's mobile app on a smart Phone (and I know which customers user the bank's mobile app).  So maybe it is not 100% deprecation.  Not perfect, but if I limit its usage, I reduce the overall risk of this authenticator.

**Suggested Change**:   So maybe it is not 100% deprecation, based on above comments.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other    2

**Comment by jricher** [comment]
That's the nature of deprecation, which many people are misinterpreting as "ban". Even if this document were an absolute mandate (it's not, this document is guidance), it would still mean "if you have something better use it instead".

**Comment by jimfenton** [comment]
There are also bank customers who do not have mobile phones at all, and some who do but have text messaging disabled because of abuse. There are several other types of authenticators available that could be used for these customers or more widely if avoiding the use of SMS.

As @jricher says above, this guidance is not imposing a ban on the use of SMS as an authenticator, but is recommending the use of alternatives in case SMS authentication is removed in a future edition of this guidance.

See also issue #19 for further discussion/info.
