### ISSUE TITLE
Future - Advice on reset link entropy 

### ISSUE THREAD

**Issue by Firstyear** [usnistgov/800-63-3#1998]
Account recovery is an important aspect of identity management. There are many situations where a user should be provided with a link or one-time-password/code in order to access a credential reset mechanism.

Since this reset mechanism is effectively a bearer token which depending on implementation may need to be human-typeable, it may be possible to brute force it during the time window that the recovery link is available.

As a result, it would be good to see advice on the amount of entropy required for such a link to reduce the likelihood of it being guessed.

**Comment by jimfenton** [comment]
Account recovery isn't called out separately because it is just an alternative way to authenticate. As such, account recovery techniques fall under the general authentication guidelines.

Certain authenticators, particularly look-up secrets, are particularly well suited to account recovery situations and have specified entropy and verifier storage requirements. If the user is provided with an authentication secret (e.g., link or one-time authentication secret), it would be considered to be an out-of-band authenticator, which requires 20 bits of entropy. Note that 800-63B section 5.1.3.1 does not permit out-of-band secrets to be sent via email or using a VoIP connection because the intent is to prove possession of a specific device, and these mechanisms do not accomplish that.

This repository is not closely monitored, so in the future please direct questions to dig-comments@nist.gov.

**Comment by Firstyear** [comment]
@jimfenton I think it deserves a call out, or at least key words included in the document, because trying a text search I was unable to find this information in the document :(

**Comment by jimfenton** [comment]
See also the discussion of account recovery in the SP 800-63 Implementation Resources at https://pages.nist.gov/800-63-3-Implementation-Resources/63B/Lifecycle/
