### ISSUE TITLE
LOA 2 (non-pseudonymous) Invalid Mapping Combo

### ISSUE THREAD

**Issue by TerryMcBride** [usnistgov/800-63-3#20]
**Organization**: 1

**Type**: 

**Reference (Include section and paragraph number)**:  
First Table within "Backwards Compatability to M-04-04 Levels of Assurance" Executive Summary in 800-83-3

**Comment (Include rationale for comment)**: 
The row for LOA 2 Non-Pseudonymous say IAL 2 and AAL of 1 which is an invalid combination in the very next table - "Acceptable IAL and AAL Combinations."  Agencies that do an M-04-04 risk assessment and land on Risk Level 2 (non-pseudo) will expect to be able to use IAL 2 and AAL1, which does not appear to be what you want.

**Suggested Change**: 
Change the AAL to 2.  That way whether agency risk assessments land on Risk Level 2 or 3, IAL 2 and AAL 2 are required.  This aligns with that short version of what I heard NIST wants to do: get rid of LOA 2.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
Duplicate with Issue #3.  We didn't do map to how we want old LOA's to map to new IAL/AAL.  We will do so in next iteration and clean this up.  Thanks for the issue!

**Comment by jimfenton** [comment]
Terry, good catch.

Part of the issue here is that there are two ways of looking at the LOA to IAL/AAL mappings:
1. Mapping between the existing LOAs and 800-63-2 requirements and the corresponding IAL and AAL
2. Mapping between LOAs and new IAL and AAL that are compliant with Executive Order 13681

The table at the end of the Executive Summary of 800-63-3 currently is the first of those. As you note, there is no difference between LOA 1 and LOA 2 pseudonymous, because we don't have different AALs for level 1 and 2 -- we need to focus on stronger, primarily two-factor, authentication.

EO 13681 requires multi-factor authentication and an effective identity proofing process for all transactions that make personal data available to citizens. Since those are typically handled at LOA 2, LOA 2 will need to require multi-factor authentication in the future. In addition, access to the attributes involved in proofing may also be considered "making personal data available", so the proofing process needs to be bound to authenticators (or perhaps a multi-factor authenticator) suitable for that task.
