### ISSUE TITLE
Derived Credentials

### ISSUE THREAD

**Issue by jaspenc** [usnistgov/800-63-3#201]
**Organization**: 2

**Type**: General

**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: Section 6.5.1

**Comment (Include rationale for comment)**:  It is my understanding that the existence of a derived credential is reliant on the credential holder's continuing authorization to hold the primary credential from which the derived credential is derived (it is the reason that the original credential is regularly checked).  The definition and the General Requirements seem to have missed this nuance.  For clarity, and to prevent misunderstanding or confusion, recommend this point be made explicit.
(*Editorial - the numbering is off in this section.)

**Suggested Change**:  Update Section 6.5.1 (and/or the definition of Derived Credential) to state something along the lines of:  "Derived Credentials SHALL be valid only as long as the subscriber is authorized to hold the original credential."

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
I'm not sure in all use cases this should be true.  For derived PIV, absolutely, but with private/public sector CSPs, users should be able to move freely from one CSP to another, without necessarily proofing all over.  This of course is up to the trust framework, and CSPs, but we shouldn't stifle that.  So perhaps there is a way to achieve both.  In shorthand we could add:

The CSP SHOULD check if user is still authorized to hold primary - SP 800-157 profiles this and makes it a SHALL.
And if RP's are worried about multiple derivations, we can add 'CSP SHOULD maintain metadata regarding the number of derivations from primary.'

In this case, when original is revoked, any derived don't necessarily need to be revoked.  Again, in PIV land they would be, but in market they don't have to be.  If I derived a credential at a private sector CSP off of my valid PIV, just because I leave government doesn't mean I should lose that credential. So again, we can add 'Derived MAY be revoked when primary is..' and SP 800-157 profiles and makes this a SHALL.

**Comment by jaspenc** [comment]
Perhaps it's the definition of "derived" that is causing me pause.  The term was devised for PIV and carries some PIV baggage (the suitability piece).  So, if you're adapting it for the non-PIV community, I think what you're suggesting is that the identity proofing associated with the original credential is being leveraged for the issuance of a secondary credential.  I don't want to say derived, because the intent is not necessarily to have a substitute credential for environments where the original can't go, which is clearly the intent of Derived PIV, and the reason for the use of the term 'derived' in this context.  Unfortunately, the problem still exists.  If the original identity proofing is invalidated for some reason, then it would seem any downstream secondary credential that relied on that identity proofing for issuance would invalidate.  I'm not sure what LOA in the marketplace would consider such an event insignificant.  The problem is that, as you suggest, an individual could leave a company (for example) and no longer be authorized to hold the company credential but the identity proofing event upon which the secondary credential is based is still valid because the individual's employment status is not a factor (I suggest that for a 'derived' credential, it is a factor).  There's just no way to differentiate these two events.  May I suggest that what you are proposing should not carry the 'derived' moniker.  It doesn't really fit the bill - you want to leverage existing identity proofing events for the issuance of a new credential, which is a good idea on its face and makes sense to do.  But calling it derived just muddies the waters.

**Comment by hferraio** [comment]
The concept of Derived credential in 63-2 (not -3) was a 'general' case, in that any original credential (for which ID proofing has been done), can be used to derived another credential (at same or lower LoA level).  So, I don't think the derivation concept should apply only to PIV.  PIV only adopted what was already in 63-2.

I believe 63-2 also had the concept of 'loosely coupled' and 'strongly coupled' derived credentials.  For PIV, we choose 'strongly coupled' in that the derived PIV credential has to be revoked when cardholder is not eligible for the original credentials (PIV card).  I feel these concept (both loosely coupled and tightly coupled) have merit in the next gen of 63 --- 63-3.

Hildy

**Comment by paul-grassi** [comment]
Yes, many of us are debating this term and will seek alternatives without screwing up anything downstream.

**Comment by paul-grassi** [comment]
What about derived for the use case it is meant for, and "inherited" or "antecedent" for proofing? The flip side here is that standards (or SP) should be use case driven, and so far, we don't have a use case for "inherited", or whatever you want to call it, proofing.  When we do, maybe we spend the cycles.
