### ISSUE TITLE
Smartphone/Mobile device/phone as a Authentictor

### ISSUE THREAD

**Issue by BlankenshipG** [usnistgov/800-63-3#210]
**Organization**:2

**Type**:Comment

**Document (63B)**:

*_Reference *_:5.1.3. Out of Band 5.1.4. Single Factor OTP Device 5.1.5. Multi-Factor OTP Devices

*_Comment *_: The draft allows for a mobile devices to be the method that the OTP is either provided to or is generated from.  The standard does not define any controls that must be around the mobile device to validate that they have not been Rooted/Jailbroken or otherwise compromised.  When a device has been compromised as such any OTP sent could be intercepted or sent to a third party.

**Suggested Change**:
## Require a method to detect such a action and deny that device to be used as a OTP source or generator.

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
As the text currently stands, it says, "This includes software-based OTP generators installed on devices such as mobile phones." While mobile phones are commonly used at present, I recall having seen OTP generators on desktop platforms such as Windows and OSX. In requiring a non-jailbroken device, would you also suggest a prohibition on OTP generators on other sorts of platforms?

Requiring platforms not to be rooted/jailbroken implies certain security properties of the platform in its default state, such as strong isolation between applications and perhaps review of all applications installed on the platform to detect malware. Also, is there a reliable way to detect jailbreaking?

**Comment by BlankenshipG** [comment]
OTP generators do exist on other software platforms such as Windows, OSX, *nix, etc.  However they would be generally precluded since the general use case for such a install would be using that device to access the data; which in those cases it would not be a second factor.  When one looks to device to be used in the context of a second device so in which it would meet the second device requirement.

All smartphone, they all have the ability to detect a root or jailbreak reliably natively, and do something it is more of a matter of someone enabling it and setting rules around it. This also would extend to other software platforms such as Windows, OSX, *nix, etc.

 One should tie the OTP device to LOA and AAL in a tier structure.  In saying that a device that is acting as a OTP for a LOA of 1 and and AAL of 1 would require less security around it then a device that is acting as a LOA 4 and OTP 3 device.  I would say a authenticator that requires a LOA of 3 or higher and a AAL of 2 or higher some kind of technical controls must be put in place to assure the security level of the OTP device has not been tampered with. 

 This is not to say that a requirement for LOA 1 and AAL 1 does not require it but it shows a understanding.  That as commercial standard such as FIDO are rolled out in masses and more commonly and widely accepted, that one is not required to manage all devices in which a OTP is used on.

**Comment by jimfenton** [comment]
It is not generally possible to require detection of compromise for software-based authenticators because some authenticators, notably multi-factor software cryptographic authenticators (typically client certificates), would have no way of implementing such protection. However, we will add text suggesting that platform compromise detection be provided when practical, and that software-based authenticators should decline to operate if they do detect a compromise.

Of course these provisions do not apply at AAL 3 where a hardware-based authenticator is required.

Note that there is no "second device" requirement: software-based authenticators may reside on the same hardware as is being authenticated. In the case of out-of-band authenticators, it is the communication channel, not the hardware, that needs to be separate and the device being communicated with needs to be uniquely identified.
