### ISSUE TITLE
Address Confirmation: Why email but not VOIP

### ISSUE THREAD

**Issue by TerryMcBride** [usnistgov/800-63-3#23]
**Organization**: 1

**Type**:

**Reference (Include section and paragraph number)**: 800-63-A, Section 4.5.5,
•May be sent to a mobile telephone (SMS or voice), landline telephone, email, or physical mailing address verified records
•SHALL NOT be sent to any form of software-based (i.e., VoIP) telephone number. 

**Comment (Include rationale for comment)**:
If you are willing to accept a non-self-asserted email, why not software based VOIP?  Both have similar properties of being able to login with relatively low security to a IP-based server to access the message.

**Suggested Change**:
Allow VOIP for address confirmation or remove email

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by pjez** [comment]
Implementing the second bullet point referenced above may be a practical impossibility.  Even if the CSP manages to determine whether a number provided for voice or SMS transmission is assigned to a software-based service, it will be unable to know or control the full delivery path.  For example, a user may have set his cell phone number to forward to his Skype number before traveling internationally.  The CSP sends the enrollment code to the mobile number, and it is forwarded to the VOIP number.  Another example:  The CSP sends the enrollment code to a landline phone, where it is left on voicemail.  The user then retrieves the voicemail over a VOIP service.

To meet the requirement, the CSP would have to be able to determine in advance and prevent changes to the full technical path the voice or SMS message will take to its ultimate destination--the eyes or ears of the user--before taking the decision to transmit the enrollment code.  The CSP will be unable to prevent changes to the full path via technical means since the user controls part of the path.  Further, for practical purposes, the CSP will be unable to prevent changes to the full path through policy means, as most users lack sufficient understanding of the concept of VOIP and providing sufficient education at or prior to the point of need would introduce unacceptable usability barriers from the point of view of the user and the CSP.

**Comment by paul-grassi** [comment]
Will adjust to account for parity between email and VOIP.
