### ISSUE TITLE
MF OTP is 2FA or just 1FA?

### ISSUE THREAD

**Issue by wangxjnj** [usnistgov/800-63-3#234]
**Organization**:

**Type**:

**Document (63-3, 63A, 63B, or 63C)**:63B

**Reference (Include section and paragraph number)**:5.1.4, 5.1.5

**Comment (Include rationale for comment)**:
 Suppose that  two WEB based banking applications both require 2FA. The app1 is protected by password + 1FA OTP, and the app2 is protected by MFA OTP.  So both of them meet the 2FA requirement.  But are they truly protected by 2FA?  From an attacker’s point of view the app1 is 2FA since it requires what you know and also what you have. But the app2 is just protected by 1FA: what you have.  Which app is more attractive to attacker and vulnerable to the attack?  The answer is very obvious: app2. 

The MFA OTP gives user a false sense of stronger security. 

Debit card is truly 2FA since the card is verified physically by the ATM(what you have is truly what you have).  A physical 1FA OTP token is verified in-directly(what you have is blindly trusted by the verifier since the OTP provided matches the expected number). For the MFA OTP it is very similar to the physical 1FA OTP except it is protected by a 1FA. So it makes “what you have” is  “what you have” with some certainty. But verification is still in-direct and also weaker than ATM card verification.

For me the “what you know or what you are” to unlock the authenticator just proves that you are the authenticator owner. So Verifier has more confidence that what you have is what you have (but a lucky guess cannot be ruled out) . 

**Suggested Change**:
##  I would like to suggest that the MF OTP should not be used alone as MFA. And the number of Factors (or how strong the authentication flow) should always be calculated from an attacker’s point of view.

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by BobPinheiro** [comment]
I believe that this issue boils down to whether the relying party can distinguish between a single factor OTP device, and a multifactor OTP device.  I don’t believe the relying party can make that distinction, since I don’t believe it can determine whether the OTP was generated after the device was first unlocked by means of an independent authentication factor such as a PIN/password or biometric.  All the relying party sees is the OTP, which could have been generated by a single factor OTP device.  If it’s not possible for a relying party to determine whether the device was first unlocked by means of a PIN/password or biometric before the OTP was generated, then it would seem that multifactor authentication at any of the Authenticator Assurance Levels cannot be achieved solely through the use of a multifactor OTP device.  If I’m wrong, and there really is a way for the relying party to determine whether the OTP was unlocked by means of an independent authentication factor, this needs to be explained somewhere in 800-63B.

Contrast this to the situation involving a multifactor cryptographic device.  In that case it is possible for the relying party to determine whether the private key on the device was unlocked by means of a separate authentication factor.  For example, the FIDO Alliance U2F protocol specifies that the type of device can be identified to a relying party by means of public / private attestation key pair that is unique to a specific vendor’s device type.  Since cryptographic authentication works by means of a challenge / response protocol, the attestation public key could be transmitted to the relying party in the response (signed by the attestation private key) that the device provides to the relying party.  The attestation keys would allow the relying party to determine whether the device is truly a multifactor cryptographic authenticator by associating the attestation public key with vendor product specifications for the device.

**Comment by wangxjnj** [comment]
Agreed! The RP cannot tell whether the OTP submitted is delivered by SMS, from 1F OTP device,  "MF" OTP device or just a lucky guess. 

FIDO has two standards: UAF and U2F.  You are referring to UAF?

**Comment by BobPinheiro** [comment]
I was referring to U2F.  The attestation keys should allow a relying party to discover characteristics of the U2F device in order to determine whether the device meets the relying party’s needs.  But on the other hand, the only U2F devices I know of are designed to plug into a computer’s USB port, and provide only single factor, cryptographic authentication.  In other words, the something-you-have factor.   I’m not aware that there is any multifactor U2F device that can be unlocked with a PIN or biometric, although I don’t know why there could not be, if some vendor wanted to make one.  But I guess that would go against the idea that U2F was designed to provide only a second, cryptographic authentication factor to enhance shared-secret passwords. 

UAF seems to be geared for smartphones running apps.  The private key in the UAF client on the smartphone can be unlocked with a PIN or biometric, when then allows for two factor authentication to the app.  But as far as I know, UAF wasn’t designed to enable a smartphone to act as a multifactor authentication device for accessing websites from a PC.

**Comment by wangxjnj** [comment]
yes the attestation key is the indicator that the claimant holds a specific vendor device (what you have is what you have with high confidence).

The UAF requires local device auth.  Is that really adding security?  A user can not access to the mobile apps without unlocking the device.  Duplicating the unlocking process for every auth request necessary? For me that is bad UX.  Why not SSO?  Some one may argue that the device may be unlocked by PIN, and UAF may require Bio.  An attacker can register his Bios on the unlocked device to meet whatever requirements by the UAF.  So in my view once the device is unlocked the game is over.  The device is  what you have if you can unlock it.  Wrong?

**Comment by rlin1** [comment]
Some comments:

> A user can not access to the mobile apps without unlocking the device
> 1. Not all users have enabled their device lock.
> 2. There exist different device lock methods (swipe the slider, pattern, PIN, ...)
> 3. How could a _remote_ server know and to what extend it can trust that the legitimate user is in front of the relevant app?  Using FIDO is a simple and secure way of proving that to a remote server.
> 
> Duplicating the unlocking process for every auth request necessary
> This depends on the scenario.  Let's assume you have a smartphone that you sometimes share with your kid for playing games.  Let's further assume you have some payments app installed.  You might want to prevent your kid from triggering payments (even though you are ok with generally sharing your phone).
> So there are scenarios in which a "fresh" user verification makes sense.  It typically depends on the risk how trustworthy the "proof of user consent" needs to be.
> 
> An attacker can register his Bios on the unlocked device to meet whatever requirements by the UAF. 
> Typically (and for a good reason) enrolling additional biometrics (or changing the PIN) to an authenticator requires a "fresh" user verification.

One more general comment:
It might lok like just terminology, but it is more: It is the Authenticator maintaining the keys and verifying the user and the authenticator might be (small) a part of a smartphone or it might be a separate device.  The complexity of an authenticator is typically much smaller than the complexity of a rich operating system (like Android, Windows or iOS).  It is easier to protect systems with smaller complexity than it is to protect systems with larger complexity.

**Comment by wangxjnj** [comment]
Device protection should be requirement for FIDO if it is not. The protection makes what you have is what you have. And a shared device  is no longer what you have any more. "fresh" auth is not going to stop the attacker registering his bios since he knows how  to unlock the device. 

The UAF should provide the same user experience like the U2F:  press a button to sign the request.

**Comment by jimfenton** [comment]
This discussion needs to separate OTP authenticators from FIDO authenticators. FIDO authenticators are single-factor (U2F) and two-factor (UAF) cryptographic devices, not OTP authenticators.

In the case of cryptographic authenticators like U2F and UAF, the attestation certificate should provide enough information to have confidence as to whether it is a single-factor or multifactor authenticator. This is a harder problem for OTP devices, because there isn't a way to securely provide this information in the authenticator output, which is typically 6-8 characters. Most likely it will be necessary to vet the device when it is associated with the user's account to determine what type of device it is. Typically these authenticators are associated with some information from their manufacturer to allow the OTP to be verified; this information would probably include information from the manufacturer about device type. But this warrants further consideration.

**Comment by wangxjnj** [comment]
I raised another issue "OOB using SMS is not OOB #215".  Got rejected. Same logic can be applied to it. It is just OTP over SMS, and OOB is not part of the OTP vefirication.

**Comment by jimfenton** [comment]
OOB and OTP are two very different things. For OTP, the authenticator and verifier are independently calculating the value of the authenticator output, and the verifier compares what it receives from the claimant to what it calculated. For OOB, the verifier generates a random value and compares it with a value received from the claimant (various different message flows are possible here).

The fact that an OTP authenticator is multifactor is established by the CSP/verifier when the authenticator is associated with the account. This typically involves an interaction with the CSP or verifier with the manufacturer of the authenticator, in order to get the secret value(s) necessary to independently calculate the authenticator output. During this interaction, it receives and makes a trust decision on an assertion from the manufacturer that it is, in fact, a multifactor authenticator. There is not a mechanism to transmit this value at authentication time, but that isn't necessary.

We will add text requiring the CSP/verifier to make this determination.

**Comment by jimfenton** [comment]
Resolved by #347.

Note also that MF OTP authenticators alone do not provide protection against verifier impersonation attacks, so will not be sufficient at AAL 3 even though they are MF. This change is currently in the works; see https://github.com/jimfenton/800-63-3/commit/7ea140ddea1c4747aa460bc4655ab8337abefd9e
