### ISSUE TITLE
Definitions - Multi-Factor 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#247]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63-3 

**Reference (Include section and paragraph number)**: 
Section 3 - Definitions and abbreviations

(KI Ref: KI/ADG#03)

**Comment (Include rationale for comment)**: 
We support the change from token to authentication but recommend it be done carefully to maintain the distinction between a hardware authenticator and a logical authenticator.  The definitions also need more clarity on authentication factors and how they relate to authenticators. Please consider the modified and added definitions to help clarify.

**Suggested Change**: 
Multi-Factor: A characteristic of an authentication system or an authenticator that requires more than one authentication factor. Example: a Multi Factor Hardware Cryptographic Authenticator consisting of a cryptographic key activated by a biometric or a password.

**Comment by ergood** [comment]
For consistency I'd suggest that the definition should reference "_types of_ authentication factors" or alternately that "authentication factors" should be defined without reference to the phrase "types of". 

While the text is generally clear that it's referring to leveraging multiple "types of" authentication factors, the stand alone definitions don't state this. Defining use of "factors" and then separately referencing "types of" factors in the adjacent (or referenced) text block could reasonably be read to imply that multiple "_types of_ authentication factors" are not required (for someone going only by the definition statements).

**Comment by jimfenton** [comment]
It's also important to point out that multi-factor authentication can be done through the use of either a single multi-factor authenticator or two separate authenticators of different factors. Some consider the latter to be "two-step" rather than multi-factor authentication so this should be made clear. I left out the example because I don't think there's any confusion about that.

Removed "types of" -- agreed, this is inconsistent terminology.
