### ISSUE TITLE
Biometrics

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#271]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  General

**Reference (Include section and paragraph number)**: 
Section  - Biometrics

(KI Ref: KI/ADG#29)

**Comment (Include rationale for comment)**: 
Discussion of biometrics is scattered across all of the documents.  Strongly recommend an additional document in the 800-63 suite discussing biometrics in a similar depth as identity proofing, authentication, federation and assertions.

**Suggested Change**: 
Include a section on biometrics.

**Comment by vanderaj** [comment]
Biometrics for one user, under control by that user, is acceptable. But biometrics as a factor fails the most basic of authentication requirements:

You cannot revoke your biometric credentials in case of breach
Body parts covering off someone else's risk is never ethically acceptable
The devices need to be guarded and tamper proof (think Smart Gates at borders) 
Cheap devices are worse than almost every other form of authentication

I'd really prefer biometric references to be isolated to one clearly written section to allow biometrics for those who can manage them properly (e.g. immigration borders) or for those who can create them for the user to accept the risk and manage for themselves (such as TouchID or Hello) on an isolated device, where the consequences of false positives, false negatives, biometric marker compromise and revocation are much less risky and in control of the subject.

**Comment by jimfenton** [comment]
[Section 5.2.3 of -63B](https://pages.nist.gov/800-63-3/sp800-63b.html#biometric_use) was intended to be the central discussion of biometrics. More discussion can be added there if you have specific suggestions, but biometrics are but one authentication factor. There may be other documents on biometrics that can be referenced if appropriate.

**Comment by enewt** [comment]
@vanderaj - You raise many points that have previously been reasons for NIST to not address biometric use in 800-63.  While biometrics as an authentication factor (rather than as an identifer) is still maturing and evolving, we thought it made sense to address biometric requirements in this update because the sensors are so much more prevalent than they were just a year or two ago.  Also, the use of biometrics that has been allowed (locally to unlock MFA) is not adequately addressed.  

To address your four specific points above in the same order:
1. We have dealt with this in two ways.  First, a biometric can never be used for single factor authentication in this draft of 800-63.  Second, in fact there are ways to "revoke" stored biometric data. There's a large body of work and some products available on biometric template protection (aka revockable biometrics). If the biometric is stored on a server (rather than locally, in control of the subject), this draft of 800-63 does require revocation methods to be used (aka biometric template protection). 
2. If this point is related to revokability, I believe the points above address this.  If something else is meant, please say more.
3. We agree that the device needs to be authenticated and that spoof detection, aka presentation attack detection needs to be present and certified on the biometric device.  This is dealt with in this draft of 800-63.
4. It's unclear how this point relates to biometrics specifically, but please feel free to explain more, keeping in mind that 800-63 is not going create requirements around cost.

In your last paragraph, I would summarize your arguement as a request to not allow centralized storage of biometrics for authentication. But you are ok with it being done locally (given the parameters that 800-63 has and that I have walked through above).  Is this a fair conclusion?
