### ISSUE TITLE
Identity evidence 

### ISSUE THREAD

**Issue by KantaraInitiative-IAWG** [usnistgov/800-63-3#280]
**Organization**: Kantara Initiative

**Type**: 2

**Document (63-3, 63A, 63B, or 63C)**:  SP 800-63A

**Reference (Include section and paragraph number)**: 
Section 5.3.1.1  - Discussing scoring identity evidence

(KI Ref: KI/ADG#38)

**Comment (Include rationale for comment)**: 
Evidence of identity appears to be leaning towards physical evidence objects - is this intentional?  Many of the source documents are speaking about in person proofing event, so physical evidence was referenced, but how are other modes of evidence to be evaluated?

**Suggested Change**: 
Clarify the discussion of identity evidence.

**Comment by paul-grassi** [comment]
Like the UK, we anticipate the need for an operational manual that goes into implementation specifics.  But we have opened the door to many remote validation and verification techniques.  Our hope is that TF providers like Kantara will help agencies profile this guideline in order to support the appropriate choices of evidence types, as well as verification and validation techniques, that will work for the target population of users.
