### ISSUE TITLE
The standard mentions PBKDF2 can be used in accordance with any approved hashing algorithm. This includes SHA-3. 

### ISSUE THREAD

**Issue by cloud101** [usnistgov/800-63-3#287]
**Organization**: 3

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**:  5.1.1.2. Memorized Secret Verifiers

**Comment (Include rationale for comment)**:

This implies SHA-3 can be used for key-derivation. This is less than ideal as SHA-3 will be significantly faster than both SHA-1 and SHA-2 and takes half the operation of calculating the HMAC. SHA-1 and SHA-2 are Merkle-Damgård schemes, which allows for the so-called "length extension attack", that makes h(k||m) a weak MAC.  This is why HMAC does the double-hashing thing. SHA-3 does not need the double invocation to be a secure MAC, making it faster than the other two. Furthermore while SHA-3 is generally slower in software, a common attacker will generally use FPGA or ASIC to perform the operations, making it almost 4 times faster than the two other SHA. 

**Suggested Change**:

Explicitly exclude SHA-3 or define which hashing primitives are allowed.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by burr44** [comment]
It is true that SHA-3 is lightning fast PRF in dedicated, custom hardware.  SHA-3's throughput to area ratio is very high in either ASIC or FPGA implementations.  So if you make the assumption that your attacker is using custom cracking hardware targeted at SHA-3, then you would need a  bigger iteration count for SHA-3 than SHA-2 or SHA-1.  But the performance of SHA-3 and SHA-2 on typical web servers is roughly comparable.  I think we can be quite certain that  a build from scratch custom ASIC password cracker for SHA-3 will have a higher throughput per dollar, than a similar SHA-2 start from scratch effort.

But the SHA-2 password crackers probably aren't starting from scratch, because there is, as I understand it, an existing moderately mature commercial market for SHA2 Bitcoin blockchain mining engines, which are probably readily adaptable to SHA-2 password cracking.  Bitcoin is probably never going to SHA-3, and I question whether a commercial market comparable to Bitcoin mining will ever exist for dedicated SHA-3 password crackers.

A better thought might be that NIST should revise SP 800-132 to incorporate and encourage the use of memory consuming password hashing schemes, such as Scrypt, that require a lot of memory and memory accesses to change the balance of power between dedicated hardware password crackers and general purpose servers (which necessarily have lots of memory and are good at accessing it).  These are going to be comparatively much more expensive in dedicated ASICs or FPGAs, than the mainly computation intensive scheme we now have, however fast the underling PRF is in dedicated hardware.

**Comment by cloud101** [comment]
@burr44  I agree that I'd have preferred to see scrypt, bcrypt or even the new algorithm which won the password  hashing competition (https://password-hashing.net/)  Argon2, to be used instead. It actually has properties like memory cost, parallelism and a time cost to be resistant against distributed hashing environments.

I understand that for the sake of compatibility NIST aims to support those algorithms which use certain hash primitives, but I personally feelm, like you, that the above mentioned algorithms should at least be included as a preferred option over PBKDF2.

**Comment by jimfenton** [comment]
While scrypt, bcrypt, and Argon2 look to be promising alternatives, the guideline can't recommend the use of cryptographic algorithms that haven't been thoroughly vetted. We have seen many algorithms that have looked promising, but had fatal flaws under further analysis.

We have noted the interest in the community for evaluation of these algorithms, and are passing that request on to the appropriate teams at NIST. Acceptance of additional algorithms will occur through updates to SP 800-132.

With respect to SHA-3, our intent in this guideline was not to get down to the level of individual hashing algorithms but allow that definition to come from SP 800-132 so that only one place needs to change as algorithms are accepted and deprecated. While SHA-3 is faster, the information we have is that it isn't enough faster to seriously weaken offline attack protection. We are also encouraging the use of a keyed hash so that one does not need to protect against brute-force attacks unless the key is also compromised.
