### ISSUE TITLE
Term CSP is Overloaded

### ISSUE THREAD

**Issue by jim-thomson** [usnistgov/800-63-3#292]
**Organization**: 3

**Type**:

**Document (63-3, 63A, 63B, or 63C)**: 63C

**Reference (Include section and paragraph number)**: Section 2, and throughout

**Comment (Include rationale for comment)**: Section 2 begins with "Assertions are statements from a credential service provider (CSP) …" but this is either too restrictive or the definition of a CSP is too broad.

800-63A and 800-63B state that a CSP is "A trusted entity that issues or registers subscriber authenticators and issues electronic credentials to subscribers. The CSP may encompass verifiers that it operates. A CSP may be an independent third party, or may issue credentials for its own use." But Verifiers also could be independent from the CSP; it should be enough to be institutionally "trusted" and to be able to authenticate claimants.

**Suggested Change**: Return to the current 800-63's use of Verifier (or a synonym) to separate the functions of issuing credentials from that of issuing authentication assertions.

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
This should be made more consistent. The difficult thing is that the term of art is "IdP" but we need to align with the rest of the document. @jimfenton any thoughts on what the right label to use in lieu of IdP is throughout -C?

**Comment by paul-grassi** [comment]
It's ok to use Idp and state why we chose that over csp, used in the other docs. Or stick with csp and we can add qualifying language. I don't want csp to get in the way in -c

**Comment by jim-thomson** [comment]
Just to clarify, it's CSP I find problematic, not IdP. In my mind, IdP is fairly bland and can connote authentication and [reachback for] providing attributes. It's the "Credential Service" connotation that limits the Verifier (to use the old term) to be the credential issuer.

**Comment by paul-grassi** [comment]
We are trying to not deviate from FICAM TFS, which lumps proofers and authenticator (token) managers into one unit. Like it or not, that's how they did it.  And in practice, the CSP for FICAM TFS does all the wonderful things we have laid out in -C.  If you have new suggestions (you should also look at -3) we are all ears, with the hope we can have these edits trickle down to the next version of FICAM TFS.  No reason we can't make that request given the relationship we have with GSA and the fact that this suite of documents pulled privacy out of FICAM TFS.  Have at it.

**Comment by jim-thomson** [comment]
Paul, et al:

I looked through several FICAM TFS documents, looking for how they used CSP and what other term they used for the Verifier. The third document is the problematic one, as you likely know.

1)      FICAM TFS Approved Identity Services, at https://www.idmanagement.gov/IDM/s/article_detail?link=approved-identity-services uses the term CSP for credential providers.

2)      Functional Requirements for FICAM SAML 2.0 Web Browser SSO Profile v1.0.2 states early on “Requirements and expected results apply to both SAML Relying Party (RP) and Credential Service Provider (CSPs) or Token Manager (TM)” and almost entirely uses “CSP/TM” in its requirements. Unfortunately, there is no glossary, so it’s not clear if “Token Manager” is a synonym for a [hard] token issuer or a synonym for an assertion issuer.

3)      Relying Party Guidance for Accepting Externally-Issued Credentials, Version 1.1.0, defines a CSP as an “entity that establishes an individual’s identity and links the identity to a credential. CSPs validate the identity of the individual using the credential and pass along verification of the individual’s identity to an RP.”, thus combining the two functions under one term. This document would require a fair number of replacements of CSP with whichever term was chosen for the authentication element.

Terms
Candidate terms include the following:
Term

Assessment

Authenticator Manager

Not bad, but too many syllables

STS

Too tied to WS-Trust

Token Manager

Can be confusing whether it’s a hard token or a soft token

Verifier

On the one hand, it’s somewhat vague and doesn’t say anything about issuing assertions. On the other hand, it’s the legacy 800-63-2 term and not an overloaded term.

I lean towards sticking with Verifier.

Jim Thomson
MITRE
703-983-1949

**Comment by paul-grassi** [comment]
Take a look here and check out the component column.  https://www.idmanagement.gov/IDM/s/article_content_old?tag=a0Gt0000000Sfwe

But, not to be flippant because we love you and all the feedback from the community, terminology nits is a bottomless pit that I prefer to avoid.  What about 'CSP that verifies'?  Either way, we've explained in many places in the document what we mean when we mention actors at a high level vs. their specific components.  And if you are a federation operator, and you see "verifier" and not IDP or CSP or OP, we will get the opposite comment.  So:  did we properly abstract roles and get the actors right?  I would say yes.  Did we get the functions of the actors right?  I would say yes.  Did we get the requirements right?  I would say yes but more comments welcome and certainly coming.  Did we allow for shifts in the marketplace?  I also would say we did, but again, comments still coming.  Did we specify completely incorrect terms and actors?  I would say no. 

If we missed any requirements by using an overloaded or too abstract term, please let us know.  If we need informative materials that demonstrate appropriate use of synonyms, let us know as well.
