### ISSUE TITLE
Backwards Compatability to M-04-04 Levels of Assurance

### ISSUE THREAD

**Issue by trbouma** [usnistgov/800-63-3#3]
Government of Canada

I may not understand the new model, plus I am testing out the comment capability here are my comments anyway.

**Executive Summary**

In the table showing the mapping back to M04-04 I see no difference between Level of Assurance 1 and 2 (pseudonymous)

**Suggested Change**:

I suggest that the table be simplified by combining Level 1 and Level 2(pseudonymous) and stipulating that Level 2 is non-pseudonymous.
 
You may wish to re-title the first column as Level of Assurance Requirement (or Assurance Level Requirement)

 I am also concerned about the potential confusion between the different levels - I will look at this more closely.

Tim

**Comment by jimfenton** [comment]
Tim,

It depends on which Executive Summary you're looking at. They are indeed the same in [SP 800-63B](https://pages.nist.gov/800-63-3/sp800-63b/cover.html), but [SP 800-63-3](https://pages.nist.gov/800-63-3/sp800-63-3/cover.html) shows it better: pseudonymous LOA 2 is IAL 1, and non-pseudonymous is IAL 2 (both are AAL 1).

We thought it important to include both types of LOA 2 because they're defined in earlier editions of SP 800-63, and we wanted to show the migration path. M-04-04 doesn't explicitly refer to pseudonymous LOA 2, but says (at the end of 4.2), "As general matter, anonymous credentials are appropriate for Levels 1 and 2 only," which I suspect is the source of pseudonymous LOA 2.

**Comment by pgrassi-nist** [comment]
Jeremy pointed out that while we are backward compatible we haven't specified how to map M0404 if it doesn't change. We want LOA 2 to be IAL/AAL2 going forward so we should make that clearer.

**Comment by trbouma** [comment]
@pgrassi-nist @jimfenton  	

Some more comments. Not necessarily an issue, but I am trying to succinctly map the model back to what we are doing in Canada. There are two issues that I am currently grappling with.

1) Is there really a difference between Level 2 (pseudonymous) and Level 2 (non-pseudonymous) that justifies separated rows? I am trending toward the answer of 'No', but I need to do more analysis.

2) There is a 'quantum leap' in requirements between IAL1 and IAL2. What NIST defines as IAL2 is equivalent to our IAL3 and what we define as IAL2, NIST bypasses completely. 

In summary, here are our different IA levels.

IAL1 (same in NIST) - acceptance self assertion
IAL2 (not defined in NIST) - acceptance of assertion by individual, with one instance of evidence of identity
IAL3 (maps to IAL2 in NIST) - acceptance of assertion by individual, with two instances of evidence of identity PLUS confirming foundational evidence of identity at source, with AT LEAST ONE confirmation method
IAL4 (maps to IAL3 in NIST) - acceptance of assertion by individual, with three instances of evidence of identity PLUS confirming foundational evidence of identity at source with AT LEAST THREE confirmation methods

What we observed is that there is a whole class of services (IAL2) that rely on the basic honesty of the individual, presenting his/her own evidence of identity and does not require a rigorous in-person or remote verification process. Examples include registering for a national job application service, that requires your real name, that you exist, etc., but does not require the same rigour as applying for a passport.

More generally, we concluded that the four levels in OMB M04-04 were basically sound. What we did though was to decouple the essence of the level definitions and graft them on to Identity and credential assurance level definitions. We also added a range of harms to the definitions - that is, if there was a compromise (identity and/or credential) it could result in a potential harm (e.g., nil to minimal for Level 1, etc.). I've mapped them below:
		
    	        OMB M04-04	                  TB Standard 
                (Confidence Required)      (Expected harm due to compromise)
Level 1	Little or no confidence	   Nil to minimal 
Level 2	Some confidence	          Minimal to moderate 
Level 3	High confidence	          Moderate to serious
Level 4	Very high confidence	  Serious to catastrophic

More to come.

**Comment by jimfenton** [comment]
Tim,

1. It has always been a little confusing to me that there were both pseudonymous and non-pseudonymous flavors of LOA 2, so it seemed clearer to break out the two almost as if they were two different LOAs. I'm concerned that if we take that out, there will be questions about what to do with pseudonymous uses of LOA 2. Does leaving it in cause a problem?

2. We observed that the differences in proofing requirements between LOA 2 and LOA 3 are minimal. We therefore decided to merge them into IAL 2. We also need to be responsive to [Executive Order 13681](https://www.whitehouse.gov/the-press-office/2014/10/17/executive-order-improving-security-consumer-financial-transactions), which requires "that all agencies making personal data accessible to citizens through digital applications require the use of multiple factors of authentication and an effective identity proofing process, as appropriate." While your example of a job application service might not involve making personal data accessible, I'm wondering how many applications the US Government would have that meet those requirements and can't be accommodated at IAL 1. On the other hand, if we added an intermediate level, we would need to be clear to agencies that anything less than the current NIST IAL 2 should not be acceptable under the terms of the EO.

**Comment by mschleiff** [comment]
I agree with trbouma about "2) There is a 'quantum leap' in requirements between IAL1 and IAL2." 
IAL1 says: "The CSP SHALL NOT proof any applicants."
IAL2 requires 2 pieces of strong evidence, or 1 piece of strong evidence plus 2 pieces of adequate evidence.
These requirements imply there is no assurance value to any of the following: 
- Proofing with just a single piece of strong evidence. 
- Proofing with just a single piece of strong evidence and a single piece of adequate evidence. 
- Proofing with 2 pieces of adequate evidence.

**Comment by TerryMcBride** [comment]
800-63-2 says: "At Level 2, the identifier associated with the Subscriber may be pseudonymous but the RA or CSP shall retain the actual identity of the Subscriber."
So, there does not appear to be a difference between LOA 2 pseudo and LOA 2 non-pseudo with respect to IAL. The CSP needs to know the "actual identity of the Subscriber" at IAL 2.  The only difference is that the relying party receives the pseudo identity information.

**Comment by jimfenton** [comment]
@TerryMcBride You're correct that there is a difference between pseudonymous LOA 2 and AAL 1/IAL 1 because in the former case the CSP has the actual identity of the subscriber (but isn't revealing it to the relying party) but in the latter it says that identity proofing shall not be performed. In the former case it isn't clear what the CSP is allowed to do with the identity information it has, so in the draft we're not assuming it has any.

One thing the specification needs to do a better job of is to distinguish between the maximum IAL/AAL of a subscriber and the IAL/AAL required by an RP for a given transaction. For example, a transaction that is pseudonymous (therefore IAL 1) should be able to use a CSP that has identity proofed the subscriber at IAL 2 or 3. The wording that at IAL 1 "The CSP SHALL NOT proof any applicants" (-63A, section 4.4) really means that the CSP isn't allowed to require identity proofing at that level, not that it can't handle a transaction at IAL 1 if it has done proofing.

**Comment by paul-grassi** [comment]
Fixed in pull request #41.  We will not be adding another IAL and have also stated requirements for LOA's moving forward.

**Comment by paul-grassi** [comment]
This will require a change to -A and -B as well in order to demonstrate future requirements of LOA to IAL/AAL, presuming OMB M-04-04 remains in place when 800-63 goes final.
