### ISSUE TITLE
Password Entropy Recommendation 

### ISSUE THREAD

**Issue by Reed-Stone** [usnistgov/800-63-3#30]
**Organization**:  Idaho National Laboratory

**Type**:3

**Reference (Include section and paragraph number)**: SP 800-63b, Appendix A, section 3 "Password Complexity" 

**Comment (Include rationale for comment)**:
 I like how the document pushes back on the idea of requiring the use of specific charter types and periodic changes. I agree that these were inadequate however, they were an attempt to ensure minimum password quality and the current document outlines little to replace it.

**Suggested Change**:
Consider adding a recommendation for organisations to measure and set minimum entropy bit threshold for passwords. where "entropy bits" is log2 of the maximum number patterns based on the characters and length of a given password. 

Obviously, this could be considered outrageous as a requirement but as a suggestion it should encourage the industry down this path. 

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
The approach of SP 800-63B is to emphasize length of memorized secrets rather than to place too much faith in what are arguably flawed attempts to measure entropy. The measure of "entropy bits" you propose is valid only if the passwords are uniformly distributed, but user-chosen passwords are far from that. See, for example:
M. Weir, S. Aggarwal, M. Collins, H. Stern, [_Testing Metrics for Password Creation Policies by Attacking Large Sets of Revealed Passwords_](www.cs.umd.edu/~jkatz/security/downloads/passwords_revealed-weir.pdf), Proc. ACM CCS 2010
J. Bonneau, [_The science of guessing: analyzing an anonymized corpus of 70 million passwords_](www.umiacs.umd.edu/%7Etdumitra/courses/ENEE759D/Fall13/papers/Bonneau12.pdf), Proc. IEEE Security&Privacy 2012

Requirements for specific character types in passwords (composition rules) have been shown to be far less effective than earlier thought. Accordingly, SP 800-63B recommends (section 5.1.1.2, paragraph 4) that user-chosen passwords instead be tested against a dictionary of passwords collected from previous breaches. This would include poor password choices such as `Password1!` which would satisfy many commonly-used composition rules.

**Comment by Reed-Stone** [comment]
Fair enough. As big a fan as I am of automatically generated 128 bit+ entropic passwords I can see your point. Thanks for the papers. Having given more thought to this (and written and erased this reply more times than I care to admit) I think enhancements to the black list would be a higher priority and an entropy check would be a distraction.
