### ISSUE TITLE
Increase minimum password length to 11+ characters

### ISSUE THREAD

**Issue by amadeuspzs** [usnistgov/800-63-3#331]
**Organization**:
 Decoded
**Type**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
 5.1.1.1
**Comment (Include rationale for comment)**:
`Memorized secrets SHALL be at least 8 characters in length`

Given the much needed shift to strong authentication represented in this document, why not increase the minimum length to at least 11 characters, based on readily accessible rainbow tables having 10 character hashes calculated [1], if not longer? 

Is there an educational role in promoting the use of password generators to generate strong passwords, eliminating the need for weak minimum password lengths?

**Suggested Change**:
`Memorized secrets SHALL be at least 11 characters in length`
`Memorized secrets SHALL be at least 12 characters in length`
...
`Memorized secrets SHALL be at least 14 characters in length`

---

Organization: 1 = Federal, 2 = Industry, 3 = Other 

[1] http://project-rainbowcrack.com/table.htm

**Comment by jimfenton** [comment]
See #96. Protection against offline attacks like this would require substantially longer memorized secrets. This guideline is taking the approach of protecting the hashes (through use of keyed hashes and/or multiple rounds of an approved key derivation algorithm) instead of incurring the usability impact of requiring memorized secrets to be longer.
