### ISSUE TITLE
Inconsistent Definitions

### ISSUE THREAD

**Issue by JimClendonDIANZ** [usnistgov/800-63-3#335]
**Organization**: 3

**Type**:

**63A, 63B**: 63A, 63B

**Reference**: 3. Definitions and Abbreviations

**Comment**: 63A uses 'Knowledge Based Verification', 63B uses 'Knowledge Based Authentication' yet the definition for 'Knowledge Based Verification' states that 'This is often referred to as knowledge based authentication (KBA)'

**Suggested Change**:  Use one of the other, not both

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
The use of the term Knowledge Based Authentication in 63A is a reference to the fact that some have used that term in the context of identity proofing, even though strictly speaking it is not an authentication process. The term has been included there to help relate the term Knowledge Based Verification to the use of KBA by others.

The term Knowledge Based Authentication is no longer used in 63B because it is no longer considered an acceptable means of authentication (previously covered under pre-registered knowledge tokens). We will remove this unnecessary definition.

**Comment by JimClendonDIANZ** [comment]
Hi

Thanks – my plan is to support  this standard and suggest it as the replacement for our NZ Government Password Standard, the NZ Government ICT standard for customers accessing services on-line.  It was last published in 2006 with some amendments in 2008.  It’s well overdue for some attention.

Jim Clendon

Jim Clendon  | AoG Enterprise Architect – Modelling and Standards | System Transformation | Service and System Transformation
The Department of Internal Affairs Te Tari Taiwhenua
147 Lambton Quay
Mobile: +64 27 4 527 463 | www.ict.govt.nzhttp://www.ict.govt.nz | www.psi.govt.nzhttp://www.psi.govt.nz

[DIAlogo]
