### ISSUE TITLE
SP 800-63B(r3) uses imprecise length constraints in §5.1

### ISSUE THREAD

**Issue by GaryGapinski** [usnistgov/800-63-3#35]
**Organization**: NASA

**Type**: 1

**Reference (Include section and paragraph number)**: SP 800-63B(r3) §5.1 multiple locations

**Comment (Include rationale for comment)**:
There are quite a few length constraints of the sort "…Memorized secrets SHALL be at least 8 characters in length…". This, coupled with the inclusion of Unicode (§5.1.1.2), will result in problems when characters are conflated/confused with other things such as octets, bytes, glyphs, symbols, and character encoding schemes.
E.g., the passphrase «डबल गोप्य» occupies 25 octets when encoded as UTF-8.

**Suggested Change**:
Specify length constraints in octets or some other suitably precise unit independent of any character encoding. Eschew assumption or explication of character encoding schemes (unless one wishes to don the hair shirt of normalization specification).

**Comment by jimfenton** [comment]
The intent here is to provide foreign language users with an opportunity to create more memorable memorized secrets, rather than to minimize the required length. The intent is that at least 8 Unicode code points are required; that way, the length requirement does not depend on the encoding mechanism chosen. We will make that more explicit in the text since the word "character" may be ambiguous in this context.
