### ISSUE TITLE
Annotate risk of use of Multi-Factor Software Cryptographic Authenticator

### ISSUE THREAD

**Issue by SES-SSE** [usnistgov/800-63-3#43]
**Organization**: 1

**Reference (Include section and paragraph number)**:
4.2.1. Permitted Authenticator Types

**Comment (Include rationale for comment)**:
Of the multi-factor authenticators (MFA) listed, Multi-Factor Software Cryptographic Authenticator (MFSCA) is the only multi-factor authenticator that can be totally compromised on the host from which a transaction is initiated, e.g. workstation, laptop, etc.  Depending on the transactions involved and risk profile of the hosts, one may determine that using a MFSC is not recommended and should defer to some other form of MFA.

**Suggested Change**:
## Suggest entering a footnote stating that MFSCAs can be susceptible to compromise by malware and that CSPs should perform a risk assessment to determine the risk of the use of MFSCAs based on the expected level of security of a host. 

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
Plan to address in Security chapter

**Comment by mschleiff** [comment]
Does addressing  it in the security section provide a way to differentiate between assurance of MFSCA and assurance of MFSCA and the other level 2 authenticators? I think a 4th level is warranted (between the current level 1 and level 2). In that new level I'd place MFSCA and OOB-SMS (rather than deprecating OOB-SMS).
