### ISSUE TITLE
RPs are not always responsible for eligbility

### ISSUE THREAD

**Issue by iglazer** [usnistgov/800-63-3#47]
**Organization**: 2

**Type**: 

**Reference (Include section and paragraph number)**: 800-63-A Section 4.2 Item 1

**Comment (Include rationale for comment)**: Item 1 states that identity proofing shall not be used to determine eligibility which is fine. But Item 1 goes on to say "The RP, not the CSP, is responsible for collecting and validating information for access control purposes" which is not universally true especially for federated systems. The CSP/IDP is very often in charge of which users can access which resources and the RP simply awaits an isAuthenticated signal from the IDP. 

This has further implications in Item 5. A CSP/IDP very often uses collected information to determine appropriate authorizations.

**Suggested Change**: Strike the 2nd sentence of Item 1 and reword Item 5 accordingly

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by MartinFSmith** [comment]
This comment highlights the need for a definition of RP.  It is the organization that is responsible for appropriate access to the data?  Or is it a technical object (the protected info system) or a sub-organization in an enterprise where another organization (operating the CSP) is responsible for enforcing access policy? 

I think it SHOULD be the former (the organization that has legal control of and responsibility for the protected information system), in which case the comment that the RP accepts an authZ "signal" from the CSP/IDP is incorrect (because both CSP/IDP and the protected info system are part of the RP organization.)
