### ISSUE TITLE
Throttling should be at the discretion of the verifier

### ISSUE THREAD

**Issue by iglazer** [usnistgov/800-63-3#50]
**Organization**: 2

**Type**:

**Reference (Include section and paragraph number)**: 800-63-B Section 5.1.1.2

**Comment (Include rationale for comment)**: Currently 5.1.1.2 requires a verifier to implement memorized secret guessing throttling. Both the number of guess and the time period are arbitrary. The verifier should be able to specify their own intervals and thresholds. Furthermore, referenced section 5.2.2 opens with "MAY" and not must. There is an internal inconsistency problem.

**Suggested Change**:  End the sentence at the word "account."

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jimfenton** [comment]
It's necessary for the document to specify the throttling limits (number of guesses and time period) because removing them would enable insecure implementations. The values chosen came from SP 800-63-2.
However, the normative language has been tightened up, particularly in section 5.2.2. Thanks for pointing that out.
