### ISSUE TITLE
Clarification of the use of "another factor"

### ISSUE THREAD

**Issue by hitoshikokumai** [usnistgov/800-63-3#525]
### All Fields Are Required
**Organization Name (N/A, if individual):** Individual

**Organization Type (see below for codes)**: 
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.2.3
 
**Comment (Include rationale for comment)**:  With "Biometrics SHALL be used with another authentication factor (something you have)" added, I understand that my suggestion (#374) is  substantially reflected.  Would it be difficult to present it a bit more expressly so that there would be no room for any misinterpretation?
 
**Suggested Change**:  For clarity's sake, the sentence of "Biometrics SHALL be used with another authentication factor (something you have) could be followed by "We require that both SHALL pass".
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by MassimoTornatore** [comment]
Having followed #374 thread, I share the view of hitoshikokumai.
What this thread means is that biometrics is no good when used without another authentication factor, while there are a great number of people who allege that biometrics increases security without referring to the need of another factor.  Don't you think that this issue deserves to be taken up by NSTIC blog as a major topic?

**Comment by IDmachines** [comment]
So this is not a new topic and has been addressed over time on multiple occasions going back almost 20 years, I frequently use this post and its precursor from 1998 to make the point https://www.schneier.com/blog/archives/2009/01/biometrics.html , that being the case it is still something around which there is a general lack of understanding.

**Comment by MassimoTornatore** [comment]
I note that Mr Schneier had written "Biometrics can vastly improve security, especially when paired with another form of authentication such as passwords."
It is a pity that he did not talk about the password which is deployed " alternatively"(as a fallback means) besides the one deployed " additionally (as another means. which he presumably meant)".  It was the theme of the preceding thread #374.

**Comment by hitoshikokumai** [comment]
I have tried to describe the two kinds of password usage as "password used by AND/Conjunction" and "password used by OR/Disjunction" in my earlier suggestions.  The wording suggested by Massimo, that is, "additionally-used password " as against "alternatively-used password" sound much better.  Thanks.

**Comment by enewt** [comment]
We will clarify that biometrics must be used as part of MFA - (still) at leaset with something you have due to the other requirements associated with the sensor.  

MFA is defined as follows:
Multi-factor Authentication (MFA)
An authentication system or an authenticator that requires more than one authentication factor for successful authentication. Multi-factor authentication can be performed using a single authenticator that provides more than one factor or by a combination of authenticators that provide different factors.

The three authentication factors are something you know, something you have, and something you are.


Further, section 5.2.3 imposes a limit on unsuccessful attempts and, once that number is reached, gives a choice of carrying that out through exponential delays or requiring an alternative factor that has not already been required. In other words, a different biometric modality or a password if the system is not 3-factor.
