### ISSUE TITLE
Where are the definitions of the FALs?

### ISSUE THREAD

**Issue by iglazer** [usnistgov/800-63-3#53]
**Organization**: 2

**Type**:

**Reference (Include section and paragraph number)**: 800-63-3

**Comment (Include rationale for comment)**: The concept of FAL is raised but in no subsequent document is it spelled out in greater depth. Where can we find what FAL1-3 mean?

**Suggested Change**: Add FAL to 800-63-C

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by jricher** [comment]
This is listed in section 5.3: https://pages.nist.gov/800-63-3/sp800-63c.html#sec5

**Comment by jricher** [comment]
(Not to say that couldn't be expanded significantly, we welcome feedback on the appropriate levels and their contents here.)

**Comment by jimfenton** [comment]
The FALs should probably be introduced in SP 800-63-3 as well, as we have done with IAL and AAL.

**Comment by paul-grassi** [comment]
agreed.  Accepting and assigning to Jim

**Comment by iglazer** [comment]
I was clearly in glazed eyes mode in that section. Seems like mapping those things to SAML and OIDC would make sense too

**Comment by iglazer** [comment]
Yes please

**Comment by jricher** [comment]
I agree on the mapping, will add a new issue to track that separately.

**Comment by iglazer** [comment]
It also occurs to me that the current table might need a little more granularity. For example a signed SAML assertion would be FAL3, correct? Whereas SAML with encrypted assertions is FAL4?

**Comment by jricher** [comment]
Most assertions in practice are FAL 1 or 2 with most deployments, since holder-of-key is really hard to get right and rare in practice. So your mapping would actually be 1 or 2. 

Vectors of Trust took another approach and included the delivery mechanism in addition to the assertion key type, so perhaps we should adopt that instead: 

   A0 No protection / unsigned bearer identifier (such as a session
      cookie)

   A1 Signed and verifiable token, passed through the browser

   A2 Signed and verifiable token, passed through a back channel

   A3 Token encrypted to the relying parties key and audience protected

https://tools.ietf.org/html/draft-richer-vectors-of-trust-00#section-4
