### ISSUE TITLE
63B 6.2: Security Posture Greatly Decreased in Recovery Scenarios

### ISSUE THREAD

**Issue by jweden** [usnistgov/800-63-3#544]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 6.2 paragraph 2
 
**Comment (Include rationale for comment)**: Security posture greatly decreased with current verbiage.
 
**Suggested Change**: Account recovery is a difficult topic.  I have a problem with everything in the 2nd paragraph after the first semi-colon IF I'm understanding it correctly.  Basically if there were multi-factor authentication, it can be replaced by a single authenticator including but not limited to those listed in any of the "MAY" options.  I think the options are very weak and if you have multi-factor authentication, it seems odd to mention that one possibility is to ask for "email telephone, postal" for example.  So all of these "MAY" options would weaken any of the higher assurance levels especially if they are multi-factor; furthermore, these options certainly seem quite arbitrary.

I think the fix is something along the lines of mentioning two things:

1.  A general statement: The CSP needs to plan ahead for these recovery scenarios such that the level of assurance isn't weakened by the backup or alternate authenticator.
2.  A specific statement:  the subscriber MAY use some or all of physical identification options such as driver's license or passport.  

The rationale for number 2 is that with the government Real ID law backing the integrity of the driver's license and the integrity of the passport (that I'm assuming doesn't require an argument here), these have way more legs to stand on (at least from a government point of view) in terms of replacing the level of identity assurance.

Finally, it may also be worth putting in a 3rd statement with respect to the importance of backups to account recovery and needing to have the CSP properly socialize the user about this.  Some MAY options could be having an offline-only backup with compensating, physical controls such as physically-secured (i.e. in safe deposit box), duplicate, already-authenticated options such as: alternate cryptographic device or written-down alternate private key.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Your intent is ours as well, so we will adjust the language to be clearer and not introduce vulnerabilities.  A goal in this revision is to not allow account recovery to be weaker than the authentication requirements.

**Comment by jimfenton** [comment]
Agree that this section needs work. The intent is as follows:

- Encourage CSPs to register backup authenticators to be used if the primary one is lost, stolen, broken, or compromised to minimize the need for account recovery
- No weakening of authentication requirements as a result of account recovery
- Repeat part of the proofing process (don't need to revalidate evidence, but do need to verify binding of evidence to claimant) as part of recovery. This may be onerous, which is why we encourage backup authenticators. There may be some issues where accounts that are not proofed (at IAL1) have difficulty being recovered at AAL2 or AAL3 because of the lack of evidence to lean on.

Please keep commenting as we work on this text.

**Comment by jweden** [comment]
Will try to keep an eye on this to collaborate.

**Comment by jimfenton** [comment]
Revisiting this issue following changes to the recovery language from several other issues that have been resolved.

Note that the paragraph in 6.2 (now paragraph 3) refers to the requirements for reporting a lost, stolen, damaged, or otherwise compromised authenticator, and not the requirements for replacing it. It is reasonable that the requirements for reporting be lower than for authentication, because it's important that the authenticator be quickly deactivated, and it would be a catch-22 to require that the subscriber authenticate with the thing they just lost. The requirements still need to be high enough that an attacker cannot deny service to the subscriber with bogus authenticator theft reports, however.

Replacing an authenticator is addressed in 6.1.2.3, which has been extensively rewritten as a result of comments received. Generally authenticators can be only replaced with others of the same factor, or with the third factor if two-factor authentication has been performed, with an important exception for memorized secrets. In that case two physical authenticators plus control of an address of record are required to establish a new memorized secret if it has been forgotten and there is no biometric available as a second factor. This is a bit of a compromise, but hopefully you will agree that this is a pragmatic approach to a common problem.

**Comment by jweden** [comment]
From Section 6.2:
> backup or alternate authenticator; either a memorized secret or

Regarding the "memorized secret" mentioned here:  It could have extra controls to compensate for it being a backup.  So instead of reading this verbiage and an architect thinking they are complying in the best way by asking the user for a user-generated, backup password, I'm wondering if verbiage should be added to consider further controls around this "backup" memorized secret such as those seen in the google backup codes.  This type of memorized secret has one-time use, is cryptographically pre-generated to be unique, can only be viewed by the user once, and is likely encrypted in their database.  

Verbiage like: "Because this memorized secret is used as a backup, it represents an additional attack surface; therefore, this backup memorized secret MAY contain additional security controls such as being system-generated after authentication, able to be viewed by the user once upon generation, and being unique across the CSP".

**Comment by jimfenton** [comment]
What you are describing here (a single-use system-generated secret) is a look-up secret  (section 5.1.2), not a memorized secret. Yes, those could be used to report a compromised authenticator. It's doubtful that one would want to use a memorized secret for that purpose, because if it is so rarely used, it it likely that it will not be remembered.

Binding of additional authenticators always represents additional attack surface, but almost certainly less than many of the account recovery procedures in common use.
