### ISSUE TITLE
Status of a smartphone as something you have

### ISSUE THREAD

**Issue by MassimoTornatore** [usnistgov/800-63-3#559]
### All Fields Are Required
**Organization Name (N/A, if individual):**individual

**Organization Type (see below for codes)**:
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 5.2.3
 
**Comment (Include rationale for comment)**: A smartphone held in our hand apparently belongs to "something we have". In view of this observation NIST could define the status of a smartphone with a biometric authentication in terms of the requirement of "Biometrics SHALL be used with another authentication factor (something you have)". 

Where we are making a login into a service on the network from such a smartphone, it might be possible to interpret that the said requirement is satisfied. But NIST may have a different view.

It is hard, however, to apply such interpretation to the situation where we are making an unlocking login into the very smartphone.  But NIST may have a different view.

Remark: This suggestion has nothing to do with the fact that a smartphone equipped with biometrics authentication and a fallback password authentication as a recovery mechanism is obviously less secure than a smartphone with only a pincode authentication due to the larger attack surface.
 
**Suggested Change**: For clarity's sake NIST could expressly define the status of a smartphone with a biometric authentication in terms of the requirement of "Biometrics SHALL be used with another authentication factor (something you have)", both where we are making a login into a service on the network from the smartphone and where we are making an unlock login into the very smartphone.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hitoshikokumai** [comment]
Intriguing subject. Well, I am of the view that, though not certain about the former online situation, another physical factor (e.g. SecureID token, another phone) should definitely be required as the "something you have" for the latter offline situation.

**Comment by hitoshikokumai** [comment]
Intriguing subject.  I am of the opinion that, though not certain about the former online situation, the latter offline situation should definitely require another physical factor (e.g. IC card, USB token and the likes) as "something you have".  The same should apply to personal tablets and laptop PCs.

**Comment by jimfenton** [comment]
A smartphone may indeed be "something you have", provided it authenticates itself to the verifier in one of the ways described. Authentication needs to be based on a secret embedded in the phone itself or in an application on the phone (the latter can only satisfy AAL2).

The verifier generally doesn't have any way to know how the phone was unlocked (or whether it doesn't need unlocking). Accordingly, unlocking the phone, separately from the authentication process, is not considered an acceptable additional factor. However, a smartphone application with an authentication secret that is able to access, for example, a fingerprint sensor or an API supporting biometric authentication would be considered to be a multifactor authenticator.

**Comment by hitoshikokumai** [comment]
I note that you are of the view that a smartphone with biometrics, which usually comes with a fallback password/pincode authentication as a recovery mechanism in case of false rejection, would be considered to be a multi-factor authenticator in certain use cases.

Another point that I raised is the security of a smartphone with only a password/pincode authentication (Model A hereafter) as against the security of such a smartphone with biometrics as mentioned above  (Model B hereafter).

Logic tells that Model A is securer than Model B because of the smaller attack surface (to borrow your wording) although Model A is less convenient than Model B.  However, we know that so many people wrongly believe that Model B is safer than Model A because it appears as if it involved more factors.

As Model A is securer than Model B, Model A makes a securer multi-factor authenticator where Model B can make a multi-factor authenticator.

I would like to suggest that you could add a footnote to this effect to 5.2.3. so that more of the consumers and media will have a correct understanding about the smartphone security.

**Comment by jimfenton** [comment]
Your logic would be valid if the threats against biometrics and against passwords or PIN codes are the same, but they aren't. For example, when I'm in a public place, the option to do biometric authentication denies a potential attacker the ability to learn my PIN through "shoulder surfing", after which they could snatch my phone. In this way, security is enhanced.

It's therefore not clear that the footnote you suggest is entirely accurate, and it's also not clear what it is recommending other than possibly to discourage the use of biometrics. There are also a number of places where the document suggests the registration of multiple authenticators, which might also be considered to weaken authentication since any of them could be used. But their availability avoids the need for simple "account recovery" methods that are often the weak spot in authentication. Their availability can therefore enhance overall security.

**Comment by jimfenton** [comment]
Going back to the original comment, it seems appropriate to include some discussion of phone unlocking as compared with second factor in the document, so reopening this issue to make sure that is included.

**Comment by hitoshikokumai** [comment]
. It is good that massimo’s suggestion seems to be partially accepted.

It is hard, however, for me to agree with your reasoning about my second comment in which I referred to Model A and Model B.  

There are three areas that I would like to ask for your views;  (1) Inherent characteristics of a two-door house as against a one-door house, (2) Meaningless comparison between passwords and biometrics, and (3) Nonexistent effects on account recovery

(1) Here is a 30-second video.  ( https://youtu.be/7UAgtPtmUbk )

 Please assume that the first door, which is common to both houses, is the password and the second door, which is unique to the two-door house, is the biometrics.  The second door could be far stronger or far weaker than the first one.  Whichever the case, a two-door house is always less secure than a one-door house because of the always larger attack surface.

(2) I do not think that we can judge which of the shoulder-surfing of the user’s password input and the collection of the user’s fingerprints from the devices or photos is safer or less safe than the other.  

Generally I am of the view that it is not possible to compare the strength of biometrics operated on its own with that of a password operated on its own.  There are (or could be) no objective data about the overall vulnerability of biometric solutions (not just false acceptance rate when false rejection is near-zero but also the risk of forgery of body features, the risk of use when the user is unconscious and leakage) and that of the passwords (not only that it may be as low as 10 bits or as high as 100 bits but also that it can be shoulder-surfed, otherwise stolen and leakage.)

We should build our discussions without involving such futile comparisons.

(3) It is hard to believe that the difference between Model A (authenticated by pincode) and Model B (authenticated by biometrics with a fallback pincode) has any positive or negative effect on the reliability of account recovery.  Pincodes are common to both models.

I would very much appreciate your observations about these three issues.

**Comment by hitoshikokumai** [comment]
I would like to insert the following remark between the first paragraph and the second of the (2) clause of the above comment of mine.

It should also be noted that we can manage a relatively stronger password when we recall it frequently, whereas the password that we recall occasionally only when falsely rejected by biometrics tends to be 
very weak.  In other words, biometrics could well drive users to register the easiest-to-recall easiest-to-break passwords.

**Comment by hitoshikokumai** [comment]
I would like to add that I am of the view that we can confidently state that Model A is securer than Model B.  Should you not be so confident, however, you would agree that it could be safely stated that it is not correct to claim, whether explicitly or implicitly, that Model B is securer than Model A.  

This kind of footnote is indispensable in the guidelines in view of the observation that so many people including a number of media wrongly believe that Model B is securer than Model A.

**Comment by MassimoTornatore** [comment]
Pleased that my suggestion is partially accepted.  Puzzled to see that hitoshikokumai's comment, which sounds just solid and irrefutable to me, seems to have been misinterpreted.

**Comment by MassimoTornatore** [comment]
I agaree that your observation is just reasonable and compelling.
"When a device such a smartphone is used in the authentication process (presuming that the device is able to meet the requirements above), the unlocking of that device (typically done using a PIN or biometric) SHALL NOT be considered to satisfy one of the authentication factors. This is because it is generally not possible for verifier to know that the device had been locked, nor whether the unlock process met the requirements for the relevant authenticator type."
