### ISSUE TITLE
Restore "Derived Credential" in lieu of "Derived Identity"

### ISSUE THREAD

**Issue by twbaldridge** [usnistgov/800-63-3#586]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoDMDC

**Organization Type (see below for codes)**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 63A

**Reference (Include section and paragraph number)**: 6. Derived Identity
 
**Comment (Include rationale for comment)**:

This section unnecessarily creates a new term term-of-art: "Derived Identity". It is better to maintain the continuity of terminology with the previous version of 63 and the NIST SP 800 157 to sustain the use of "Derived Credential". There is sufficient alignment between Identity and Credential to retain the section for "Derived Credential" in 63A, with the specification of the bound authenticator for a Derived Credential in 63B. 

Further while NIST SP 800-157, "Guidelines for Derived Personal Identity Verification (PIV) Credentials" specifies requirements specifically for PIV, and NIST SP 800-79-2, "Guidelines for the Authorization of Personal Identity Verification Card Issuers (PCI) and Derived PIV Credential Issuers (DPCI)" provides appropriate and useful guidelines for assessing the reliability of issuers of PIV and Derived PIV, no such guidance exists for credentials other than PIV. As a consequence a general non-PIV "Derived Credential" may be evaluated based on the "authenticator" bound to the "Primary Credential" at time of issuance of the "authenticator" for the "Derived Credential".  No binding shall exist between the authenticators of the "Primary" and "Derived" credentials' authenticators after issuance of the Derived Credential Authenticator. There is simply no governance or common authority that specifies and/or accredits the sustaining requirements beyond the initial issuance.
 
**Suggested Change**:

Appropriately restore the term "Derived Credential" throughout this section and any references to it.

Remove any requirements related required or suggested for Derived Credential Authenticator post-issuance actions based on the status of the Primary Credential Authenticator.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by LarryFrank** [comment]
The idea of a "derived" credential means there is something inherently different between this and other credentials issued based on a "non-derived" ID proofing process.  Derived should only impact the IAL.  As written, a derived ID proofing inherits the original IAL and it does not impact the AAL or FAL.  Either the current inheritance mechanism is correct or (as 800-157 does) need to attach additional requirements to maintain IAL3 when ID proofing is derived (e.g., done in person).  Frankly, that will likely result in most derived processes being categorized as IAL2 since the primary benefit of a derived ID proofing mechanism is the ability to do it without returning to an ID proofer.  Ultimately, the "credential" is what it is - IALx/AALx/FALx based on the evaluations of each of these elements.  Where those can vary in a specific technology (e.g., PKI certificates) - the credential itself needs a way to provide relying parties a way to distinguish between them.

**Comment by LarryFrank** [comment]
I see what Tim is saying but think a better answer than changing 63A would be to change 63 to defines a "derived credential" - as one which uses a "derived identity" proofing process.  The need to 800-63 to use the term is addressed but 63A only talks to identity proofing and not the overall credntial.

**Comment by jimfenton** [comment]
Going back to the term _derived credential_, but we want this to be more general than PIV, to accommodate G-to-C and G-to-B derived credentials.
