### ISSUE TITLE
AAL 3 should include MF OTP, as with older LOA 4 in rev 2

### ISSUE THREAD

**Issue by usethedata** [usnistgov/800-63-3#594]
### All Fields Are Required
**Organization Name (N/A, if individual): n/a

**Organization Type (see below for codes)**: 4
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: 4.3
 
**Comment (Include rationale for comment)**: Only permitting cryptographic authenticators at AAL 3 seems problematic and ignores the risk tradeoffs between a MF cryptographic token generator and a MF OTP token generator.  This document presents that a MF cryptographic token generator is always superior to a MF OTP token generator.  This ignores the well-known vulnerabilities where a compromised endpoint allows an adversary to present a MF cryptographic token generator as coming from the device of their choice, except in the very rare case where a secure card reader (embedded key pad) is used.  The challenge-response nature of a MF OTP generator (such as the SafeNet Gold device -- and no, I have no connection with that company) is potentially more secure in some circumstances than a MF cryptographic token generator.  Furthermore, with Linux systems and ssh chains, the operational reliability risks of cryptographic token generators are problematic and also rely on ssh-agent chaining (and the risks inherent in that).
 
**Suggested Change**: Acknowledge the security of MF OTP token generators and add these to the allowed list at AAL 3.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
AAL 3 requires that at least one authenticator be verifier impersonation resistant, and OTP devices are not. Users can be tricked into authenticating at counterfeit sites (e.g., by phishing emails) and if this occurs, the output of an OTP device could be used by the counterfeit site (attacker) to gain access to the user's account. This is true even for challenge-response OTP, since the attacker could obtain a challenge and proxy it at the counterfeit site.

Cryptographic authenticators that use the authenticated identity of the verifier (probably from a certificate) in generating the authenticator output cannot be proxied by a third party to obtain access to the user's account.
