### ISSUE TITLE
Identity Proofing of Homeless Person

### ISSUE THREAD

**Issue by deantonio** [usnistgov/800-63-3#63]
800-63-3A IAL2 and greater always requires address verification.  Has any consideration been made about how someone who is homeless can be identity proofed?  This has come on multiple occasions in various VA discussions regarding how a homeless Veteran could get a credential (http://www.va.gov/homeless/index.asp).

**Comment by taprootsec** [comment]
I support consideration of this issue. Perhaps unintended, but as currently structured the 800-63 framework denies access to medium or high assurance services by individuals without a postal address.

**Comment by rsfaron23** [comment]
I agree.  many poor and recently immigrated people, sometimes college students, etc.  have no permanent address, or just a P.O. Box.  Address based identity proofing will not work for many populations.
The solution absent a national identity card is difficult, but may need to involve privacy challenging data mining of social media, or perhaps links to telephone data.

**Comment by paul-grassi** [comment]
@deantonio we are going to schedule some time with the VA as we understand a CSP is being stood up to specifically support this population.  Because of that, I will likely move resolution of this issue to Iteration 3.  For clarification, we removed the postal requirement at IAL3.  At IAL2, more than just postal is allowed, but I don't want to close this just because of those allowances.

**Comment by paul-grassi** [comment]
Fixed by pull #312
