### ISSUE TITLE
High Entropy Reusable Passwords

### ISSUE THREAD

**Issue by BobPinheiro** [usnistgov/800-63-3#656]
Section 5 of 800-63B specifies three types of secrets: memorized secrets, lookup secrets (which are high entropy passwords stored on some device or card, each of which can only be successfully used once), and one-time passwords.  The requirements for authentication at AAL2 are clear that some form of multifactor authentication is required, and in particular, one of those factors can be a “something you know” memorized secret.

The problem is that many people use password managers that are able to generate and store complex, high entropy passwords.  Since these passwords are too complex for most users to memorize, for all practical purposes they are lookup secrets, with the password manager acting as a lookup device.  But they don’t fit into NIST’s definition of a lookup secret, because they are reusable passwords and not single-use secrets.  Hence by default they fall into the category of memorized secrets, even though most people wouldn’t be able to memorize them.  

How should complex, high entropy passwords generated by a password manager be treated?  One possibility is to ignore the issue entirely, and just treat these passwords as memorized secrets.  Although memorized secrets as well as high entropy passwords are both susceptible to keystroke logging, phishing/man-in-the-middle, and social engineering attacks, high entropy reusable passwords are generally more resistant to brute force attacks and dictionary attacks than memorized secrets.  So there is some value in distinguishing between memorized secrets and high entropy reusable passwords.  

Another point to consider is that using a memorized secret as a “something you know” authentication factor arguably provides weaker security when it is used directly with a relying party than when it is used to unlock a device in the user’s possession, such as a multifactor OTP device, a multifactor cryptographic device, or a password manager.  That’s because a memorized secret used to unlock a user’s device never leaves the device, whereas a memorized secret used directly with the relying party is more susceptible to compromise.  

In light of these points, I propose that NIST consider the following changes to 800-63B:

(1) Define a “high entropy reusable secret” as consisting of some minimum number of characters together with some requirement for entropy, to be consistent with the capabilities of today’s password managers.

(2)	Consider reducing the number of required characters in a memorized secret from 8 to something smaller.  

(3)	Eliminate the use of memorized secrets except to unlock a user’s device; that is, memorized secrets should only be used in conjunction with a multifactor OTP or multifactor cryptographic device / software. 
 
(4)	At both AAL1 and AAL2, replace memorized secrets currently used as single “something you know” authentication factors with a high entropy, reusable password.  This would require users to either have a very good memory, or to use password managers to generate and recall high entropy passwords (which still requires a memorized secret to unlock the password manager).  A possibility exists that this may result in users maintaining two memorized secrets: one to unlock the password manager, and another to unlock a multifactor OTP or cryptographic device.

**Comment by jimfenton** [comment]
The definition of _memorized secret_, and its accompanying requirements (length, etc.) are based on the concept that it be something that is able to be memorized by the user (even if the user may not actually commit it to memory). We do have a distinction between that and a _key_, which is required to have (currently) at least 112 bits of entropy, although as you note none of the authentication protocols allow a key to be used (reusably) as an authenticator output.

To your individual suggestions:

(1) There isn't a case for something between a memorized secret and a key in complexity. As you note, reuse of even a more complex secret directly as a reusable authenticator is vulnerable to threats like key loggers, limiting their strength.

(2) No, especially since (3) is also a no.

(3) Single factor authentication based on memorized secrets, while not as strong as one would like, still has utility for applications with very modest risk. Forcing those applications to multi-factor authentication would be an enormous burden. We are focusing on moving applications that have non-negligible risk to multi-factor.

(4) While we are acknowledging the use of password managers in various ways, they have their own risk associated with them and it would be inappropriate to set requirements that effectively mandate them.
