### ISSUE TITLE
AAL-3 too restrictive and unattainable

### ISSUE THREAD

**Issue by FacePhiResearch** [usnistgov/800-63-3#663]
### All Fields Are Required
**Organization Name (N/A, if individual): Facephi

**Organization Type (see below for codes)**: 2
 
**Document (63-3, 63A, 63B, or 63C)**: 63B

**Reference (Include section and paragraph number)**: Section 4.3. Authenticator Assurance Level 3
 
**Comment (Include rationale for comment)**: AAL3 requires a “hard” cryptographic authenticator (assumed to mean hardware based), putting additional roadblocks to meet requirements on small and medium companies that provide SW-based authentication solutions to the market, plus making it almost impossible to use current and commonly used smartphones and other mobile devices (like iPads and Tablets) that are normally sealed and not customizable, for information accessing.

Any standard must acknowledge the trade-off existing between security and usability, considering that one of the most important drivers (if not the most important one) for adoption of mobile biometric solutions is the actual demand and the easy of use for end-users. Biometrics and specifically biometrics on mobile devices is normally selected as the main mean of authentication due to the pervasiveness and high penetration rates of such devices among users.

HW-based authenticators are not only expensive but difficult to implement and maintain, which could result in less use by end-user, that way defeating the purpose of additional security since fewer users will use that particular mean of authentication. As stated in the NIST Internal Report (NISTIR) 8103  "Advanced Identity Workshop on Applying Measurement Science in the Identity Ecosystem: Summary and Next Steps" of September of 2016,a poor user experience is a vulnerability by itself

Therefore, we propose that instead of requiring a HW-based cryptographic authenticator, AAL3 requires, as an added security level above AAL2, the use of another factor of authentication like voice or fingerprint, plus the incorporation of “liveness” testing —the ability for a biometric system to determine if the biometric being presented is from a live authorized person—during authentication.

 
**Suggested Change**: We suggest the following text in section 4.3:
Replace: “AAL3 is like AAL2 but also requires a “hard” cryptographic authenticator that provides verifier impersonation resistance.”

with: “...AAL3 is like AAL2 but also requires a second factor of authentication that could be voice or fingerprint authentication, plus a “liveness” test as part of the authenticator that provides additional verifier impersonation resistance.”
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
AAL3, like LOA4 in previous editions of SP 800-63, will continue to require a hardware-based authenticator because it is not vulnerable to many software threats. Note that AAL3 is required for authentication only when there is the potential for significant harm or impact as a result of a false authentication, so would probably not be needed by most citizens.

There is a strong likelihood that some smartphones containing secure elements (in particular where the authentication secret is inaccessible to the software) would be suitable at AAL3 as well.

Finally, liveness detection is currently nascent -- we don't have enough experience to know how effective it is in many biometric modalities, which accounts for why it is not required although it may be in the future.
