### ISSUE TITLE
On secure storage of keys

### ISSUE THREAD

**Issue by BrJu** [usnistgov/800-63-3#674]
### All Fields Are Required
**Organization Name (N/A, if individual):**
Safran IS
**Organization Type (see below for codes)**:
 2
**Document (63-3, 63A, 63B, or 63C)**:
63B
**Reference (Include section and paragraph number)**:
 5.1.3.1, 5.1.6.1, and 5.1.8.1“The key used SHALL be stored in the most secure storage available on the device (e.g., keychain storage, trusted platform module, trusted execution environment).”
**Comment (Include rationale for comment)**:
The most secure storage is not always accessible to developers. Thus one should mention that the requirement is on the storage options that are usable and accessible. 
The storage is not sufficient in general if one cannot execute the cryptographic algorithms inside the storage. In that case, it could be possible to find a place to store the key that offers both reasonably good security and the possibility to execute the algorithms directly within it. 
**Suggested Change**:
 Replace "in the most" with "in a"

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jweden** [comment]
I've been thinking about this too.  So I think there needs to be more clarity around storage requirements for keys as per this issue and #610.  The use of the verbiage "most secure storage available" and "e.g." (which just lists some examples) leaves the door too wide open to interpretation.  So we should list the specific storage requirements including access controls around how they are accessed manually and, more importantly, programatically.  I know there are NIST documents around key management but we should delineate the specific key management and storage requirements list in this document since those other docs incorporate many use cases.

**Comment by jimfenton** [comment]
With the range of platforms being used, it is difficult to be more specific. It might have said "store keys someplace good and secure" but that would have been both more vague and less clearly normative.

The idea is that many platforms have mechanisms, both hardware and software, for storing keys. For example, In some cases, this "keychain" is not backed up, eliminating key compromise through disclosure of the backup as a threat. But describing this is difficult, in part because different platforms use different terminology, and because we don't want to create a situation where some platforms can't be used because there isn't such storage on them.

"most secure storage available" means storage that is accessible to the software or through an API that provides the necessary operations (signing, etc.).

Perhaps this whole statement is common sense and doesn't even need to be included, but it's useful to remind implementers of the need to consider where the keys are kept.

Will look at what can be done to clarify "available".
