### ISSUE TITLE
Security Controls from 800-53

### ISSUE THREAD

**Issue by mschleiff** [usnistgov/800-63-3#72]
**Organization**: 2

**Reference (Include section and paragraph number)**: Sectioins 4.1.5, 4.2.5, 4.3.5, and table in 4.4

**Comment (Include rationale for comment)**: I really like that 800-63 has separate components for IAL, AAL, and FAL. This allows a CSP’s efforts in one area to be recognized even if their effort hasn’t yet addressed all areas. The biggest problem with 800-63 is that it requires the security controls of 800-53 in order to recognize any assurance value of the authenticators used. For example, even authentication with multi-factor cryptographic device would have no assurance value unless the CSP also meets some baseline level of 800-53. And. If the CSP meets only the Low Baseline of 800-53, then the AAL can only be level 1, regardless of if the authentication was based on multi-factor crypto device or just single factor password.

**Suggested Change**: Segregate AAL into two separate categories. Remove the Security Controls requirements from 800-63B. Create a 4th assurance category based on 800-53. Maybe call it Controls Assurance Level (CAL) or something like that. Use the low/med/high baselines of 800-53 as CAL 1/2/3.

**Comment by skswave** [comment]
This is a great point. The Trusted computing technologies of TPM and the newer trusted execution technologies of Intel SGX and ARM trustzone provide tremendous real world value. Certification of these platforms has proven challenging both for the supply side and the customer. The result is that government opts for Windows protected keys in a FIPS 140-2 level 1 container vs leverage the TPM for the last decade.  It is important to provide a clear preference to hardware protected keys. Perhaps just at the same level of assurance but NIST should be strongly declarative on this statement and help industries investment in these technologies. It is a public private partnership that has invested billions but consistently customers across all of industry call out that hardware can't be leveraged due to certification.  The goal needs to be certified hardware but the path to that goal is still uncertain after 2.5 billion shipped devices.

**Comment by mschleiff** [comment]
Just changing SHALL to SHOULD? I guess that means it can be ignored as a factor of AAL. Now the table in section 4.4 should be tweaked, because the Security Controls are no longer required. I know I don't always get what I want, but I sure would like to see a separate component for security controls. I guess for my use cases I'll be able to use AAL (without security controls) and use 800-53 baselines as a separate component that I'll call Controls Assurance Level. Too bad that I'll have to have a deviation from 800-63; I was hoping I could use 800-63 without further qualification.

**Comment by mschleiff** [comment]
Actually, I should be happier than I sounded in my prior comment on this topic. By removing the requirement for Security Controls (well, changing from SHALL to SHOULD), you are giving me the freedom to not include security controls in AAL, which allows me to use an alternate way to represent security controls assurance level. So, Thanks! Your change is actually pretty effective and allows me a way to satisfy my requirements.

**Comment by paul-grassi** [comment]
Thanks for your feedback, participation, and candor.  A weak compromise, but one just the same, is to mark this as a future consideration.  We've explicitly stated in -3 that we are Fed focused, but attempting a strong alignment with other international standards.  In addition, we hope one day to bring [Vectors of Trust](https://tools.ietf.org/html/draft-richer-vectors-of-trust-00) into play, where it was explicitly decided not to add CAL, since it wasn't a transactional element.  But we appreciate the point and encourage the future dialog.

**Comment by mschleiff** [comment]
I think that 800-63 is a significant improvement over VOT specifically because you acknowledge at least some assurance benefit for having good security controls, and VOT does not. I never could understand the reasoning behind not including security controls because they are not a transactional element. By "... hope one day to bring Vectors of Trust into play", do you mean concepts like Trustmarks, how to represent LOA in SAML assertions, and stuff like that, or something else?

**Comment by paul-grassi** [comment]
Jury is still out, but we would want to be able to map an 800-63 implementation into the vectors (and their  specific component values), or allow for profiling into the vectors. Lot's of way this could occur.  And then yes, if we have a VOT "mapping" (for lack of better word) its conceivable to have trustmark and discovery working.  But I don't see that today as an 800-63 item.  I see that in trust frameworks.  Fun stuff, but we are a while away from trustmarks, I believe.

**Comment by jricher** [comment]
Just to explain some rationale here: what you're calling "CAL" here is exactly the kind of thing that's covered by the trustmark and discovery portion of VoT. It's very important, and it's part of the context that gives the other bits of information their teeth. In 800-63, it's more of a baseline implied by the context (federal use, for instance). In neither case is it something that's going to vary per user or per transaction, it's per CSP/RP. Thus we moved it to an IdP discovery element in VoT instead of a separate vector component.

**Comment by mschleiff** [comment]
800-63-3c section 4.1 describes federation models, one of which is "Brokered Federation" (section 4.1.4). In such a model there may be multiple CSPs with differing security controls (and with varying degrees of compliance with VOT and/or 800-63). The assurance level of a Broker-issued assertion must consider both the Broker's security controls and the differing controls of participating CSPs. RPs will benefit from a CAL level which can vary from assertion to assertion issued by the Broker.

**Comment by jricher** [comment]
In brokered scenarios you're generally hiding the root CSP so you're relying on the controls of the broker, which include its brokering capabilities. Leaking information about the transaction from the CSP is likely to be unwanted in many cases.

**Comment by mschleiff** [comment]
I'm trying yto understand the differences between:
- Leaking information about the transaction from the CSP is likely to be unwanted (from your last comment)
- an IdP discovery element in VoT (from two comments ago)

Is there a difference in the type of information? Why would it be worthy of discovery, and yet be unwanted? Maybe it would be unwanted in some situations, but it is wanted in my use cases.

**Comment by jricher** [comment]
Let me start by saying that I think the discussion on brokers is a red herring, but let's see it through: If you're using the discovery based approach and you're hiding the upstream CSP from the RP through a broker, then there's no leak because you can't do discovery on an upstream CSP you don't know about. 

If you're passing information through the transaction that effectively describes the CSP's practices (which is what I believe you're suggesting), then you're potentially uniquely identifying it within an ecosystem. That's the difference in information leakage -- if the broker is truly blinding the RP, then it can't divulge that kind of information. The RP ultimately has to trust the broker, and therefore it makes sense for the decisions to be made off of the _broker_'s security model more than anything else. If you're using a broker, then what you're going to do is have a discovery document on the broker itself since it is acting as the CSP for the RP in that instance. See the diagram and discussion in 4.1.4 here: https://pages.nist.gov/800-63-3/sp800-63c.html#sec4

In any case, this doesn't change the fact that the information you're describing is in nature more about the identity provider than about the identity being provided during the transaction. The question remains "how much do I trust the security practices in this CSP?" in all cases. The security practices and policies of the CSP aren't going to be different per-account or per-transaction in the way that an asserted IAL, AAL, or FAL would be. What might be different is the credential management practices, which VoT separated out into its own vector component based on community feedback. This aspect has historically been implicit in 800-63 as living in a single level for all federal transactions. This makes sense if you recall that 800-63 is first and foremost written in a federal US context. We think there's value in making it more explicit and flexible, and the commit here is the first part of that change.

**Comment by andrewhughes3000** [comment]
I agree with you Justin.
That's how we have designed the Trust Framework at DIACC. The Operators of
identity, credential and access management services must conform to a set
of common controls (privacy, security, forensic, etc. ) That's table stakes
to offer any ICAM service.
Still debating how to reflect 'levels' of controls - but that's a different
discussion.
Andrew Hughes
On Tue, Jul 5, 2016 at 4:47 PM Justin Richer notifications@github.com
wrote:

> Let me start by saying that I think the discussion on brokers is a red
> herring, but let's see it through: If you're using the discovery based
> approach and you're hiding the upstream CSP from the RP through a broker,
> then there's no leak because you can't do discovery on an upstream CSP you
> don't know about.
> 
> If you're passing information through the transaction that effectively
> describes the CSP's practices (which is what I believe you're suggesting),
> then you're potentially uniquely identifying it within an ecosystem. That's
> the difference in information leakage -- if the broker is truly blinding
> the RP, then it can't divulge that kind of information. The RP ultimately
> has to trust the broker, and therefore it makes sense for the decisions to
> be made off of the _broker_'s security model more than anything else. If
> you're using a broker, then what you're going to do is have a discovery
> document on the broker itself since it is acting as the CSP for the RP in
> that instance. See the diagram and discussion in 4.1.4 here:
> https://pages.nist.gov/800-63-3/sp800-63c.html#sec4
> 
> In any case, this doesn't change the fact that the information you're
> describing is in nature more about the identity provider than about the
> identity being provided during the transaction. The question remains "how
> much do I trust the security practices in this CSP?" in all cases. The
> security practices and policies of the CSP aren't going to be different
> per-account or per-transaction in the way that an asserted IAL, AAL, or FAL
> would be. What might be different is the credential management practices,
> which VoT separated out into its own vector component based on community
> feedback. This aspect has historically been implicit in 800-63 as living in
> a single level for all federal transactions. This makes sense if you recall
> that 800-63 is first and foremost written in a federal US context. We think
> there's value in making it more explicit and flexible, and the commit here
> is the first part of that change.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/usnistgov/800-63-3/issues/72#issuecomment-230635407,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASYM_Asj9SZwJeF295W2WGNwGRSmXMHtks5qSu0EgaJpZM4IuNLw
> .
> 
> ## 

_Andrew Hughes *CISM CISSP
Independent Consultant
*In Turn Information Management Consulting_

o  +1 650.209.7542
m +1 250.888.9474
1249 Palmer Road,
Victoria, BC V8P 2H8
AndrewHughes3000@gmail.com
ca.linkedin.com/pub/andrew-hughes/a/58/682/
*Identity Management | IT Governance | Information Security *

**Comment by paul-grassi** [comment]
We recognize that the document needs to be as agnostic to federal use cases as possible. Hence why many of the broker "requirements" are SHOULDs and not SHALLs.  However, in the federal use case, we may not need to be so advanced - though I appreciate the end-state envisioned by the experts on this thread.  A federal trust framework will ensure that every CSP meets the security controls necessary to deliver services through a hub to the federal government, so discovery and assertions of controls adherence is moot, particularly in blinded transactions.  @jricher has it right that the hub has to also meet the control requirements, but the CSPs will too.  We should account for comparability, but that is a whole different ball of wax, and why we shifted to SHOULD as well as allowance for another control frameworks - not just 800-53-current.  If the 800-63 requirements imposed on private sector CSPs are too unruly for them to do business in the public and private sector, let us know.  If the identities a public sector CSP manages (insert agency with a large population here) wouldn't be accepted in a private sector transaction because of the 800-63 controls, let us know that too.  We want to make sure all CSPs that are doing good things are able to provide services to the government.  If we missed the mark, let us know.

**Comment by mschleiff** [comment]
Security controls are only mentioned in 800-63B (AAL). Seems like security controls would be just as important to IAL and FAL. Of course I prefer that rather than mention security controls as SHOULD in each component, security controls should be a separate component of assurance.

**Comment by mschleiff** [comment]
Regarding Transactional Security Controls:

Think of IDaaS providers. For those organizations capable of being a CSP, the IDaaS is a Broker. For users of other organizations not capable of being a CSP, the IDaaS is the CSP. The pertinent security controls (i.e., controls at CSP-capable orgs, controls at non-CSP orgs, and controls at the IDaaS) all impact LOA. The IDaaS portion of security controls might be constant; however, considering the differing controls at each org, each IDaaS assertion/transaction is based on differing security controls.

I believe this view agrees with pgrassi-nist's remark that in addition to hubs, CSPs also have to meet the control requirements. I'm adding that even security controls at non-CSPs are important to LOA.

**Comment by mschleiff** [comment]
Regarding VOT:

A few days ago pgrassi-nist said, "we hope one day to bring Vectors of Trust into play". Can I assume that a way to represent 800-63 components might be similar to VOT's dot-separated list; e.g., "ial2.aal3.fal2"? Or, might you be thinking of single letter components (e.g., "i2.a3.f2") instead of 3-letter components?

**Comment by jricher** [comment]
There will definitely be a mapping of IAL, AAL, and FAL into the VoT dotted format, but it's an open question right now whether that mapping is defined in the NIST document or in an IETF document (VoT core or otherwise).

**Comment by mschleiff** [comment]
I struggle with whether or not to open a new issue, or continue on this closed thread.

My organization runs a Federation Proxy as described in 800-63-3 4.1.4 (note: the diagram still says "broker" instead of "proxy"), and also in 6.3.

A candidate RP is asking about how the proxy examines/trusts/vets the IdPs' assertion-signing certificates. The RP recognizes that different IdPs will have different practices, technical capabilities (e.g., HSM), and that they will be using certs from different CAs and even perhaps self-signed certs.  I want to answer the RP that the Proxy will consider IdP practices, technical capabilities, and signing certificates along the aspects described in section 7 (FAL), and include the resulting FAL value as a claim in the assertion to the RP.

Alternately, if IdP practices, technical capabilities, and signing certificates cannot be included as part of FAL, then I suppose I'll have to include them in a separate assurance component that is important to my use case (i.e., what I called Controls Assurance Level in previous comments). 

Note: In my use case, we're not trying to obscure or hide an upstream CSP from the RP; rather, we're trying to make it evident to the RPs that users authenticate at different CSPs, and that the use of a particular CSP impacts the resulting LOA.
