### ISSUE TITLE
bad definition of credential

### ISSUE THREAD

**Issue by TomCJones** [usnistgov/800-63-3#722]
### All Fields Are Required
**Organization Name (N/A, if individual):**

**Organization Type (see below for codes)**:4
 
**Document (63-3, 63A, 63B, or 63C)**:63A

**Reference (Include section and paragraph number)**: 3 definition of credential
 
**Comment (Include rationale for comment)**:
 First problem is that the definitions of credential and other terms used in the doc are not normative, which makes any place they are used subject to other interpretations. The definition of credential confuses it with certificate. The credential should be in the authenticator, the certificate should be the

"An object or data structure that authoritatively binds an identity (and optionally, additional attributes) to an authenticator possessed and controlled by a subscriber."

**Suggested Change**:
 Drop this sentence and make it the definition of a certificate.
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
Moving to -B.  We are also creating one master definitions file for ease.

**Comment by jimfenton** [comment]
The given definition of credential is intentional; the data structure held by the CSP is always authoritative. In some cases, the CSP may issue a certificate to the subscriber attesting to information in that data structure, but the credential exists even if that isn't done so that certificate isn't the credential as the term is used here.

We note that _credential_ is often used in a different way, which is part of the reason for defining it here.

**Comment by TomCJones** [comment]
I completely reject this interpretation. The data structure held by the CSP is not capable (when secure credentialing is enabled) to enable access by the user. Only the part held by the user is capable of acquiring access. It is even specifically possible for the use to get a different certificate from a different CSP to enable authentication using the same private keying material. If this definition stands I will become a vocal opponent of this standard's adoption by industry.
