### ISSUE TITLE
Device Centric Multi-Factor Hardware Cryptographic Devices

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#725]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID2

**Organization Type (see below for codes)**:
1

**Document (63-3, 63A, 63B, or 63C)**:
63-3B

**Reference (Include section and paragraph number)**:
5.1.7, 5.1.9.1

**Comment (Include rationale for comment)**:
Device Centric Multi-Factor Hardware Cryptographic Device should be included as an authenticator device.

**Suggested Change**:
Introduces a device centric approach option for implementing a universal identity and authentication approach across systems
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by DoD-CIO-ID** [comment]
For example, a reference to FIDO UAF might be placed in section 5.1.7.1.  
A reference to FIDO U2F might go under section 5.1.9.1.

**Comment by jimfenton** [comment]
A Single- or Multi-Factor Cryptographic Device is already device-centric; it's not clear what would distinguish a new type of authenticator.

The FIDO devices will not be specifically cited because -63B discusses authentication requirements, not implementations. However, please note the U2F would correspond most closely to 5.1.7.1 because by itself it is a single-factor authenticator. UAF would correspond most closely to 5.1.9.1.
