### ISSUE TITLE
Shoulder Surfing

### ISSUE THREAD

**Issue by DoD-CIO-ID2** [usnistgov/800-63-3#738]
### All Fields Are Required
**Organization Name (N/A, if individual):**
DoD-CIO-ID2
**Organization Type (see below for codes)**:
 1
**Document (63-3, 63A, 63B, or 63C)**:
63-3C
**Reference (Include section and paragraph number)**:
 4.1.5
**Comment (Include rationale for comment)**: The second paragraph discusses shoulder surfing, which is not relevant to Federation,  and should be deleted.

**Suggested Change**:

Go into detail about which mechanisms require masking, and circumstances where such measures would apply.  If addressing host-based protection, this appears to be outside scope.  
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
This is about an RP making a request from a CSP, in a federation, to provide attribute a,b, x with the RP.  It is beneficial for the user to actually know the _values_ being sent to the RP as it allows for an even more informed decision on whether to consent to sharing or not.  It's not enough to know that, for example, email and name is being provided.  We want users to know that email with value 'Z' and name with value 'T' is being shared, in case 'Z' and 'T' are inaccurate.  That said, we don't want these values to be automatically visible in case of various threats, to include shoulder surfing. 

A private sector example is as follows.  When I log into my bank, my routing and number is masked because it is sensitive data:

<img width="290" alt="screen shot 2017-04-06 at 9 27 51 pm" src="https://cloud.githubusercontent.com/assets/13986911/24781784/013e92b0-1b10-11e7-817b-8d101d4e3180.png">

but they offer me the ability to unmask when I want and am comfortable with.  

<img width="374" alt="screen shot 2017-04-06 at 9 30 20 pm" src="https://cloud.githubusercontent.com/assets/13986911/24781823/493f2c0a-1b10-11e7-9a21-0ba48b45ad54.png">

Same applies when attributes are going to be shared from a CSP to an RP via federation.
