### ISSUE TITLE
‘…increasing the administrative effort in managing the attribute correlation’ (relating to sensitive associations and tracking users) that may be prohibited by privacy laws/policies is not 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#885]
**Organization Name (N/A, if individual)**: National Security Agency

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63C

**Reference (Include section and paragraph number)**: 5.2.5, 2
 
**Comment (Include rationale for comment)**:  ‘…increasing the administrative effort in managing the attribute correlation’ (relating to sensitive associations and tracking users) that may be prohibited by privacy laws/policies is not sufficient. 
 
Also, this series does not impose requirements on policies. Suggest replacing ‘privacy policies MAY…’ with ‘RPs, including federation proxies, SHALL respect privacy laws/policies…’ and ‘… SHALL NOT disclose access data, attributes, or attribute claims where such disclosure would violate privacy laws/policies.’

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
We will be rewording paragraph 2 to emphasize the reasons for using pairwise pseudonymous identifiers while still pointing out the possibility of collusion between RPs. The "increasing the administrative effort" comment will be kept because this is only a supplemental characteristic; the rest of that sentence will be made more clearly normative as suggested regarding adherence to privacy policies.
