### ISSUE TITLE
IAL1 acceptable for LOA4?

### ISSUE THREAD

**Issue by ronalfs2** [usnistgov/800-63-3#95]
**Organization**: 1

**Type**:

**Reference (Include section and paragraph number)**: 800-63A 4.2 Table AND 800-63-3 Executive Summary, M04-04 LOA mapping table. 

**Comment (Include rationale for comment)**:  Table suggests that IAL1 is acceptable for LOA4.

**Suggested Change**:  If this is the intent, some explanation should be provided as to why this is acceptable.  Else, either make introduction to table more clear so that one cannot make the inference reflected in the above comment OR remove IAL1 from table in the LOA4 row. 

---

Organization: 1 = Federal, 2 = Industry, 3 = Other

**Comment by paul-grassi** [comment]
The idea is that separating ial from aal allows a strong cred but no proofing. In a case like PIV, the agency would select ial3 and aal3 but this new scheme allows all sorts of coupling. More language will be considered. Thanks for comment!

**Comment by ronalfs2** [comment]
Strong cred with no proofing makes sense for some scenarios.  It is not intuitive, however, that such a combination is an acceptable interpretation of M04-04, "Level 4:  Very high confidence in the asserted identity's validity."  Thank you for considering additional language.

**Comment by paul-grassi** [comment]
Fair enough with current definitions of level 4. We're hoping for a change there. 👍

**Comment by paul-grassi** [comment]
We expect M-04-04 to be updated, but in lieu of that, we will include specific language that true alignment with M-04-04 would require proofing and credentialing at the same levels.  However, we still want to set requirements that allow agencies to assess at a high LOA (because risk of data loss could have major negative impact) but still allow lower proofing if it makes sense.  We will provide examples.  We recognize this is a shift in requirements, but such is the state of the market. And as currently written, nothing is keeping someone from assessing at LOA4 and requiring IAL and AAL3 processes/technologies.

**Comment by ronalfs2** [comment]
"We expect M-04-04 to be updated, but in lieu of that, we will include specific language that true alignment with M-04-04 would require proofing and credentialing at the same levels."

Some IAL/AAL legitimate combinations may be lost if the above language is chosen.  For example:  An LOA2 designation for an IAL2 and AAL3 OR IAL3 and AAL2 combination might be suitable.

This said, having an LOA designation higher than the lowest assurance level of an IAL, AAL and FAL combination could be problematic.  

The suggested examples to come will hopefully promote greater understanding of an approach where the LOA is higher than the lowest assurance level of an IAL, AAL and FAL combination.
