### ISSUE TITLE
Users should be encouraged to make their passwords as lengthy as they want, within reason. 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#966]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63B

**Reference (Include section and paragraph number)**: General, Appendix A: Strength of Memorized Secrets
 
**Comment (Include rationale for comment)**:  Users should be encouraged to make their passwords as lengthy as they want, within reason.
 
Since the size of a hashed password is independent of its
length, there is no reason not to permit the use of lengthy passwords (or pass phrases) if the user wishes.

**Suggested Change**: I suggest to be more specific such as length of the password to be either 12 or 14. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See -63B section 5.1.1.2, second sentence: "Verifiers SHOULD permit user-chosen memorized secrets to be up to 64 characters or more in length." We are not giving guidelines on how to encourage users because the situations can vary widely, but will consider this for inclusion in an anticipated implementation guide.
