### ISSUE TITLE
Why is FIPS 140 certification not required for AAL2 authenticators? 

### ISSUE THREAD

**Issue by dig-comments** [usnistgov/800-63-3#991]
**Organization Name (N/A, if individual)**: Internal Revenue Service

**Organization Type**: 1
 
**Document (63-3, 63A, 63B, or 63C)**: 800-63-3

**Reference (Include section and paragraph number)**: , 
 
**Comment (Include rationale for comment)**:  Why is FIPS 140 certification not required for AAL2 authenticators?
 

**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by paul-grassi** [comment]
It is if the agency procures, builds, issues any authenticator.  It's not if a citizen/constituent brings their own (provided it meets the rest of the requirements.  This is to support innovation in the market.  For example, a user that has an authenticator app on an iOS version that is FIPS certified CANNOT upgrade to the new iOS because that puts the entire authenticator out of FIPS compliance.  It is untenable to tell stakeholders they can't update iOS due to this requirement.
